/* eslint-disable */
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Maybe<T> = T | null;
export type InputMaybe<T> = T | null | undefined;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** An ISO 8601-encoded date */
  ISO8601Date: { input: any; output: any; }
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: { input: Date; output: Date; }
  /** Represents untyped JSON */
  JSON: { input: any; output: any; }
};

export enum Attack {
  Chemical = 'chemical',
  Explosive = 'explosive',
  Mystic = 'mystic',
  Normal = 'normal',
  Piercing = 'piercing',
  Sonic = 'sonic'
}

export enum BossTypeEnum {
  Allied = 'allied',
  Raid = 'raid',
  Unlimit = 'unlimit'
}

export type Campaign = {
  __typename?: 'Campaign';
  category: Array<CategoryEnum>;
  endAt: Scalars['ISO8601DateTime']['output'];
  multiplier: Scalars['Int']['output'];
  region: Scalars['String']['output'];
  startAt: Scalars['ISO8601DateTime']['output'];
  uid: Scalars['String']['output'];
};

export enum CategoryEnum {
  BountyHunt = 'bounty_hunt',
  Commision = 'commision',
  Exp = 'exp',
  MissionHard = 'mission_hard',
  MissionNormal = 'mission_normal',
  Schedule = 'schedule',
  Scrimmage = 'scrimmage'
}

export type ContentReferenceInput = {
  contentType: ContentTypeEnum;
  contentUid: Scalars['String']['input'];
};

export enum ContentTypeEnum {
  EventContent = 'event_content',
  MainStoryPart = 'main_story_part'
}

/** Autogenerated input type of CreateCampaign */
export type CreateCampaignInput = {
  category: Array<CategoryEnum>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  endAt: Scalars['ISO8601DateTime']['input'];
  multiplier: Scalars['Int']['input'];
  region: Region;
  startAt: Scalars['ISO8601DateTime']['input'];
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of CreateCampaign. */
export type CreateCampaignPayload = {
  __typename?: 'CreateCampaignPayload';
  campaign: Maybe<Campaign>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
};

/** Autogenerated input type of CreateEventContent */
export type CreateEventContentInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  rawDataFirst: InputMaybe<Scalars['JSON']['input']>;
  rawDataRerun: InputMaybe<Scalars['JSON']['input']>;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of CreateEventContent. */
export type CreateEventContentPayload = {
  __typename?: 'CreateEventContentPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  eventContent: Maybe<EventContent>;
};

/** Autogenerated input type of CreateJointFiringDrill */
export type CreateJointFiringDrillInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  confirmed: InputMaybe<Scalars['Boolean']['input']>;
  defenseType: Defense;
  drillType: DrillTypeEnum;
  schedules: InputMaybe<Array<JfdScheduleInput>>;
  season: Scalars['Int']['input'];
  terrain: Terrain;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of CreateJointFiringDrill. */
export type CreateJointFiringDrillPayload = {
  __typename?: 'CreateJointFiringDrillPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  jointFiringDrill: Maybe<JointFiringDrill>;
};

/** Autogenerated input type of CreateRaidBoss */
export type CreateRaidBossInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  eventContentUid: InputMaybe<Scalars['String']['input']>;
  raidType: BossTypeEnum;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of CreateRaidBoss. */
export type CreateRaidBossPayload = {
  __typename?: 'CreateRaidBossPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  raidBoss: Maybe<RaidBoss>;
};

/** Autogenerated input type of CreateRaidSchedule */
export type CreateRaidScheduleInput = {
  attackType: InputMaybe<Attack>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  defenseTypes: InputMaybe<Array<DefenseTypeInput>>;
  endAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  eventContentRunType: InputMaybe<EventScheduleRunTypeEnum>;
  jpSeasonIndex: InputMaybe<Scalars['Int']['input']>;
  raidBossUid: Scalars['String']['input'];
  raidType: RaidScheduleTypeEnum;
  region: Region;
  seasonIndex: Scalars['Int']['input'];
  startAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  terrain: Terrain;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of CreateRaidSchedule. */
export type CreateRaidSchedulePayload = {
  __typename?: 'CreateRaidSchedulePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  raidSchedule: Maybe<RaidSchedule>;
};

/** Autogenerated input type of CreateRecruitmentGroup */
export type CreateRecruitmentGroupInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  content: InputMaybe<ContentReferenceInput>;
  endAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  recruitmentType: RecruitmentTypeEnum;
  recruitments: InputMaybe<Array<RecruitmentInput>>;
  startAt: Scalars['ISO8601DateTime']['input'];
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of CreateRecruitmentGroup. */
export type CreateRecruitmentGroupPayload = {
  __typename?: 'CreateRecruitmentGroupPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  recruitmentGroup: Maybe<RecruitmentGroup>;
};

/** Autogenerated input type of CreateRecruitment */
export type CreateRecruitmentInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  pickup: InputMaybe<Scalars['Boolean']['input']>;
  recruitmentGroupUid: Scalars['String']['input'];
  recruitmentType: RecruitmentTypeEnum;
  rerun: InputMaybe<Scalars['Boolean']['input']>;
  studentName: Scalars['String']['input'];
  studentUid: InputMaybe<Scalars['String']['input']>;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of CreateRecruitment. */
export type CreateRecruitmentPayload = {
  __typename?: 'CreateRecruitmentPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  recruitment: Maybe<Recruitment>;
};

export type Currency = ResourceInterface & {
  __typename?: 'Currency';
  name: Scalars['String']['output'];
  rarity: Scalars['Int']['output'];
  type: ResourceTypeEnum;
  uid: Scalars['String']['output'];
};

export enum Defense {
  Composite = 'composite',
  Elastic = 'elastic',
  Heavy = 'heavy',
  Light = 'light',
  Normal = 'normal',
  Special = 'special'
}

export type DefenseTypeAndDifficulty = {
  __typename?: 'DefenseTypeAndDifficulty';
  defenseType: Defense;
  difficulty: Maybe<Difficulty>;
};

export type DefenseTypeInput = {
  defenseType: Defense;
  difficulty: InputMaybe<Difficulty>;
};

export enum Difficulty {
  Extreme = 'extreme',
  Hard = 'hard',
  Hardcore = 'hardcore',
  Insane = 'insane',
  Lunatic = 'lunatic',
  Normal = 'normal',
  Torment = 'torment',
  VeryHard = 'very_hard'
}

export enum DrillTypeEnum {
  Assault = 'assault',
  Defense = 'defense',
  Escort = 'escort',
  Shooting = 'shooting'
}

export type Equipment = ResourceInterface & {
  __typename?: 'Equipment';
  category: Scalars['String']['output'];
  name: Scalars['String']['output'];
  rarity: Scalars['Int']['output'];
  subCategory: Maybe<Scalars['String']['output']>;
  type: ResourceTypeEnum;
  uid: Scalars['String']['output'];
};

export type EventContent = {
  __typename?: 'EventContent';
  bonuses: Array<EventContentBonus>;
  minigameConfigs: Array<EventMinigameConfig>;
  name: Scalars['String']['output'];
  rawDataFirst: Maybe<Scalars['JSON']['output']>;
  rawDataRerun: Maybe<Scalars['JSON']['output']>;
  schedules: Array<EventContentSchedule>;
  shopResources: Array<EventContentShopResource>;
  stages: Array<EventContentStage>;
  uid: Scalars['String']['output'];
};


export type EventContentBonusesArgs = {
  runType: RunTypeEnum;
};


export type EventContentMinigameConfigsArgs = {
  runType: RunTypeEnum;
};


export type EventContentShopResourcesArgs = {
  runType: RunTypeEnum;
};


export type EventContentStagesArgs = {
  runType: RunTypeEnum;
};

export type EventContentBonus = {
  __typename?: 'EventContentBonus';
  percentage: Scalars['String']['output'];
  resource: Maybe<ResourceInterface>;
  student: Maybe<Student>;
};

export type EventContentSchedule = {
  __typename?: 'EventContentSchedule';
  endAt: Maybe<Scalars['ISO8601DateTime']['output']>;
  region: Scalars['String']['output'];
  runType: Scalars['String']['output'];
  startAt: Scalars['ISO8601DateTime']['output'];
};

export type EventContentShopResource = {
  __typename?: 'EventContentShopResource';
  paymentResource: Maybe<ResourceInterface>;
  paymentResourceAmount: Scalars['Int']['output'];
  resource: Maybe<ResourceInterface>;
  resourceAmount: Scalars['Int']['output'];
  shopAmount: Maybe<Scalars['Int']['output']>;
  uid: Scalars['String']['output'];
};

export type EventContentStage = {
  __typename?: 'EventContentStage';
  enterCostAmount: Scalars['Int']['output'];
  enterCostResource: Maybe<ResourceInterface>;
  rewards: Array<EventContentStageReward>;
  stageIndex: Scalars['Int']['output'];
  stageNumber: Scalars['String']['output'];
  stageType: Scalars['String']['output'];
  uid: Scalars['String']['output'];
};

export type EventContentStageReward = {
  __typename?: 'EventContentStageReward';
  amount: Scalars['Int']['output'];
  probability: Scalars['String']['output'];
  resource: Maybe<ResourceInterface>;
  tag: Scalars['String']['output'];
};

export type EventMinigameConfig = {
  __typename?: 'EventMinigameConfig';
  minigameType: Scalars['String']['output'];
  payment: EventMinigamePayment;
  rewardGroups: Array<EventMinigameRewardGroup>;
};

export type EventMinigamePayment = {
  __typename?: 'EventMinigamePayment';
  quantity: Scalars['Int']['output'];
  resource: Maybe<ResourceInterface>;
};

export type EventMinigameRewardGroup = {
  __typename?: 'EventMinigameRewardGroup';
  condition: EventMinigameSlotCondition;
  rewards: Array<EventMinigameRewardItem>;
};

export type EventMinigameRewardItem = {
  __typename?: 'EventMinigameRewardItem';
  quantity: Scalars['Float']['output'];
  resource: Maybe<ResourceInterface>;
};

export type EventMinigameSlotCondition = {
  __typename?: 'EventMinigameSlotCondition';
  divisor: Maybe<Scalars['Int']['output']>;
  remainders: Maybe<Array<Scalars['Int']['output']>>;
  type: Scalars['String']['output'];
  value: Maybe<Scalars['Int']['output']>;
  values: Maybe<Array<Scalars['Int']['output']>>;
};

export enum EventScheduleRunTypeEnum {
  First = 'first',
  Permanent = 'permanent',
  Rerun = 'rerun'
}

export type FavoriteItem = {
  __typename?: 'FavoriteItem';
  exp: Scalars['Int']['output'];
  favoriteLevel: Scalars['Int']['output'];
  favorited: Scalars['Boolean']['output'];
  item: Item;
  student: Student;
};

export type Furniture = ResourceInterface & {
  __typename?: 'Furniture';
  category: Scalars['String']['output'];
  name: Scalars['String']['output'];
  rarity: Scalars['Int']['output'];
  subCategory: Maybe<Scalars['String']['output']>;
  tags: Array<Scalars['String']['output']>;
  type: ResourceTypeEnum;
  uid: Scalars['String']['output'];
};

export type Gear = {
  __typename?: 'Gear';
  growthItems: Array<GearGrowthItem>;
  name: Scalars['String']['output'];
};

export type GearGrowthItem = {
  __typename?: 'GearGrowthItem';
  amount: Scalars['Int']['output'];
  gearTier: Scalars['Int']['output'];
  item: Item;
};

export type Item = ResourceInterface & {
  __typename?: 'Item';
  category: Scalars['String']['output'];
  name: Scalars['String']['output'];
  rarity: Scalars['Int']['output'];
  subCategory: Maybe<Scalars['String']['output']>;
  type: ResourceTypeEnum;
  uid: Scalars['String']['output'];
};

export type JfdScheduleInput = {
  endAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  region: Region;
  startAt: Scalars['ISO8601DateTime']['input'];
};

export type JointFiringDrill = {
  __typename?: 'JointFiringDrill';
  confirmed: Scalars['Boolean']['output'];
  defenseType: Defense;
  drillType: DrillTypeEnum;
  schedules: Array<JointFiringDrillSchedule>;
  season: Scalars['Int']['output'];
  terrain: Terrain;
  uid: Scalars['String']['output'];
};

export type JointFiringDrillSchedule = {
  __typename?: 'JointFiringDrillSchedule';
  endAt: Maybe<Scalars['ISO8601DateTime']['output']>;
  region: Scalars['String']['output'];
  startAt: Scalars['ISO8601DateTime']['output'];
};

export type MainStoryChapter = {
  __typename?: 'MainStoryChapter';
  chapterNumber: Scalars['Int']['output'];
  name: Maybe<Scalars['String']['output']>;
  parts: Array<MainStoryPart>;
  uid: Scalars['String']['output'];
};

export type MainStoryPart = {
  __typename?: 'MainStoryPart';
  episodeEnd: Maybe<Scalars['Int']['output']>;
  episodeStart: Maybe<Scalars['Int']['output']>;
  name: Maybe<Scalars['String']['output']>;
  schedules: Array<MainStoryPartSchedule>;
  sortOrder: Scalars['Int']['output'];
  uid: Scalars['String']['output'];
};

export type MainStoryPartSchedule = {
  __typename?: 'MainStoryPartSchedule';
  confirmed: Scalars['Boolean']['output'];
  region: Scalars['String']['output'];
  releasedAt: Scalars['ISO8601DateTime']['output'];
};

export type MainStoryVolume = {
  __typename?: 'MainStoryVolume';
  chapters: Array<MainStoryChapter>;
  label: Scalars['String']['output'];
  name: Maybe<Scalars['String']['output']>;
  sortOrder: Scalars['Int']['output'];
  uid: Scalars['String']['output'];
};

export type MiniEventContent = {
  __typename?: 'MiniEventContent';
  name: Scalars['String']['output'];
  schedules: Array<MiniEventContentSchedule>;
  uid: Scalars['String']['output'];
};

export type MiniEventContentSchedule = {
  __typename?: 'MiniEventContentSchedule';
  endAt: Scalars['ISO8601DateTime']['output'];
  occurrence: Scalars['Int']['output'];
  region: Scalars['String']['output'];
  startAt: Scalars['ISO8601DateTime']['output'];
};

export type Mutation = {
  __typename?: 'Mutation';
  createCampaign: Maybe<CreateCampaignPayload>;
  createEventContent: Maybe<CreateEventContentPayload>;
  createJointFiringDrill: Maybe<CreateJointFiringDrillPayload>;
  createRaidBoss: Maybe<CreateRaidBossPayload>;
  createRaidSchedule: Maybe<CreateRaidSchedulePayload>;
  createRecruitment: Maybe<CreateRecruitmentPayload>;
  createRecruitmentGroup: Maybe<CreateRecruitmentGroupPayload>;
  updateCampaign: Maybe<UpdateCampaignPayload>;
  updateEventContent: Maybe<UpdateEventContentPayload>;
  updateJointFiringDrill: Maybe<UpdateJointFiringDrillPayload>;
  updateRaidBoss: Maybe<UpdateRaidBossPayload>;
  updateRaidSchedule: Maybe<UpdateRaidSchedulePayload>;
  updateRecruitment: Maybe<UpdateRecruitmentPayload>;
  updateRecruitmentGroup: Maybe<UpdateRecruitmentGroupPayload>;
  upsertEventContentSchedule: Maybe<UpsertEventContentSchedulePayload>;
  upsertJointFiringDrillSchedule: Maybe<UpsertJointFiringDrillSchedulePayload>;
};


export type MutationCreateCampaignArgs = {
  input: CreateCampaignInput;
};


export type MutationCreateEventContentArgs = {
  input: CreateEventContentInput;
};


export type MutationCreateJointFiringDrillArgs = {
  input: CreateJointFiringDrillInput;
};


export type MutationCreateRaidBossArgs = {
  input: CreateRaidBossInput;
};


export type MutationCreateRaidScheduleArgs = {
  input: CreateRaidScheduleInput;
};


export type MutationCreateRecruitmentArgs = {
  input: CreateRecruitmentInput;
};


export type MutationCreateRecruitmentGroupArgs = {
  input: CreateRecruitmentGroupInput;
};


export type MutationUpdateCampaignArgs = {
  input: UpdateCampaignInput;
};


export type MutationUpdateEventContentArgs = {
  input: UpdateEventContentInput;
};


export type MutationUpdateJointFiringDrillArgs = {
  input: UpdateJointFiringDrillInput;
};


export type MutationUpdateRaidBossArgs = {
  input: UpdateRaidBossInput;
};


export type MutationUpdateRaidScheduleArgs = {
  input: UpdateRaidScheduleInput;
};


export type MutationUpdateRecruitmentArgs = {
  input: UpdateRecruitmentInput;
};


export type MutationUpdateRecruitmentGroupArgs = {
  input: UpdateRecruitmentGroupInput;
};


export type MutationUpsertEventContentScheduleArgs = {
  input: UpsertEventContentScheduleInput;
};


export type MutationUpsertJointFiringDrillScheduleArgs = {
  input: UpsertJointFiringDrillScheduleInput;
};

/** An object with an ID. */
export type Node = {
  /** ID of the object. */
  id: Scalars['ID']['output'];
};

/** Information about pagination in a connection. */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor: Maybe<Scalars['String']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor: Maybe<Scalars['String']['output']>;
};

export enum Position {
  Back = 'back',
  Front = 'front',
  Middle = 'middle'
}

export type Query = {
  __typename?: 'Query';
  campaign: Maybe<Campaign>;
  campaigns: Array<Campaign>;
  equipments: Array<Equipment>;
  eventContent: Maybe<EventContent>;
  eventContents: Array<EventContent>;
  items: Array<Item>;
  jointFiringDrill: Maybe<JointFiringDrill>;
  jointFiringDrills: Array<JointFiringDrill>;
  mainStories: Array<MainStoryVolume>;
  miniEventContent: Maybe<MiniEventContent>;
  miniEventContents: Array<MiniEventContent>;
  raidBoss: Maybe<RaidBoss>;
  raidBosses: RaidBossConnection;
  raidSchedule: Maybe<RaidSchedule>;
  raidScheduleBySeasonIndex: Maybe<RaidSchedule>;
  raidSchedules: RaidScheduleConnection;
  raids: RaidConnection;
  recruitmentGroup: Maybe<RecruitmentGroup>;
  recruitmentGroups: Array<RecruitmentGroup>;
  student: Student;
  students: Array<Student>;
};


export type QueryCampaignArgs = {
  region: InputMaybe<Scalars['String']['input']>;
  uid: Scalars['String']['input'];
};


export type QueryCampaignsArgs = {
  endAfter: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  region: Scalars['String']['input'];
};


export type QueryEquipmentsArgs = {
  uids: InputMaybe<Array<Scalars['String']['input']>>;
};


export type QueryEventContentArgs = {
  uid: Scalars['String']['input'];
};


export type QueryEventContentsArgs = {
  uids: InputMaybe<Array<Scalars['String']['input']>>;
};


export type QueryItemsArgs = {
  uids: InputMaybe<Array<Scalars['String']['input']>>;
};


export type QueryJointFiringDrillArgs = {
  uid: Scalars['String']['input'];
};


export type QueryJointFiringDrillsArgs = {
  endAfter: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  startBefore: InputMaybe<Scalars['ISO8601DateTime']['input']>;
};


export type QueryMiniEventContentArgs = {
  uid: Scalars['String']['input'];
};


export type QueryMiniEventContentsArgs = {
  endAfter: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  region: InputMaybe<Scalars['String']['input']>;
};


export type QueryRaidBossArgs = {
  uid: Scalars['String']['input'];
};


export type QueryRaidBossesArgs = {
  after: InputMaybe<Scalars['String']['input']>;
  before: InputMaybe<Scalars['String']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  raidType: InputMaybe<Scalars['String']['input']>;
};


export type QueryRaidScheduleArgs = {
  uid: Scalars['String']['input'];
};


export type QueryRaidScheduleBySeasonIndexArgs = {
  region: Scalars['String']['input'];
  seasonIndex: Scalars['Int']['input'];
};


export type QueryRaidSchedulesArgs = {
  after: InputMaybe<Scalars['String']['input']>;
  before: InputMaybe<Scalars['String']['input']>;
  endAfter: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  raidType: InputMaybe<Scalars['String']['input']>;
  region: Scalars['String']['input'];
  startBefore: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  uids: InputMaybe<Array<Scalars['String']['input']>>;
};


export type QueryRaidsArgs = {
  after: InputMaybe<Scalars['String']['input']>;
  before: InputMaybe<Scalars['String']['input']>;
  endAfter: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  startBefore: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  types: InputMaybe<Array<RaidTypeEnum>>;
  uids: InputMaybe<Array<Scalars['String']['input']>>;
};


export type QueryRecruitmentGroupArgs = {
  uid: Scalars['String']['input'];
};


export type QueryRecruitmentGroupsArgs = {
  endAfter: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  startBefore: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  uids: InputMaybe<Array<Scalars['String']['input']>>;
};


export type QueryStudentArgs = {
  uid: Scalars['String']['input'];
};


export type QueryStudentsArgs = {
  uids: InputMaybe<Array<Scalars['String']['input']>>;
};

export type Raid = Node & {
  __typename?: 'Raid';
  attackType: Attack;
  boss: Scalars['String']['output'];
  confirmed: Scalars['Boolean']['output'];
  defenseTypes: Array<DefenseTypeAndDifficulty>;
  endAt: Scalars['ISO8601DateTime']['output'];
  /** ID of the object. */
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  raidIndexJp: Maybe<Scalars['Int']['output']>;
  rankVisible: Scalars['Boolean']['output'];
  since: Scalars['ISO8601DateTime']['output'];
  startAt: Scalars['ISO8601DateTime']['output'];
  terrain: Terrain;
  type: RaidTypeEnum;
  uid: Scalars['String']['output'];
  until: Scalars['ISO8601DateTime']['output'];
  videos: RaidVideoConnection;
};


export type RaidVideosArgs = {
  after: InputMaybe<Scalars['String']['input']>;
  before: InputMaybe<Scalars['String']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  sort?: InputMaybe<VideoSortEnum>;
};

export type RaidBoss = Node & {
  __typename?: 'RaidBoss';
  eventContent: Maybe<EventContent>;
  /** ID of the object. */
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  raidType: Scalars['String']['output'];
  schedules: Array<RaidSchedule>;
  uid: Scalars['String']['output'];
};


export type RaidBossNameArgs = {
  lang?: InputMaybe<Scalars['String']['input']>;
};

/** The connection type for RaidBoss. */
export type RaidBossConnection = {
  __typename?: 'RaidBossConnection';
  /** A list of edges. */
  edges: Array<RaidBossEdge>;
  /** A list of nodes. */
  nodes: Array<RaidBoss>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type RaidBossEdge = {
  __typename?: 'RaidBossEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node: Maybe<RaidBoss>;
};

/** The connection type for Raid. */
export type RaidConnection = {
  __typename?: 'RaidConnection';
  /** A list of edges. */
  edges: Array<RaidEdge>;
  /** A list of nodes. */
  nodes: Array<Raid>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type RaidEdge = {
  __typename?: 'RaidEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node: Maybe<Raid>;
};

export type RaidSchedule = {
  __typename?: 'RaidSchedule';
  attackType: Maybe<Attack>;
  defenseTypes: Array<DefenseTypeAndDifficulty>;
  endAt: Maybe<Scalars['ISO8601DateTime']['output']>;
  jpSchedule: Maybe<RaidSchedule>;
  raidBoss: RaidBoss;
  raidType: Scalars['String']['output'];
  region: Scalars['String']['output'];
  seasonIndex: Scalars['Int']['output'];
  startAt: Maybe<Scalars['ISO8601DateTime']['output']>;
  terrain: Terrain;
  uid: Scalars['String']['output'];
  videos: RaidVideoConnection;
};


export type RaidScheduleVideosArgs = {
  after: InputMaybe<Scalars['String']['input']>;
  before: InputMaybe<Scalars['String']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  sort?: InputMaybe<VideoSortEnum>;
};

/** The connection type for RaidSchedule. */
export type RaidScheduleConnection = {
  __typename?: 'RaidScheduleConnection';
  /** A list of edges. */
  edges: Array<RaidScheduleEdge>;
  /** A list of nodes. */
  nodes: Array<RaidSchedule>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type RaidScheduleEdge = {
  __typename?: 'RaidScheduleEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node: Maybe<RaidSchedule>;
};

export enum RaidScheduleTypeEnum {
  Allied = 'allied',
  Elimination = 'elimination',
  TotalAssault = 'total_assault',
  Unlimit = 'unlimit'
}

export enum RaidTypeEnum {
  Allied = 'allied',
  Elimination = 'elimination',
  TotalAssault = 'total_assault',
  Unlimit = 'unlimit'
}

export type RaidVideo = Node & {
  __typename?: 'RaidVideo';
  /** ID of the object. */
  id: Scalars['ID']['output'];
  publishedAt: Scalars['ISO8601DateTime']['output'];
  score: Scalars['Int']['output'];
  thumbnailUrl: Scalars['String']['output'];
  title: Scalars['String']['output'];
  youtubeId: Scalars['String']['output'];
};

/** The connection type for RaidVideo. */
export type RaidVideoConnection = {
  __typename?: 'RaidVideoConnection';
  /** A list of edges. */
  edges: Array<RaidVideoEdge>;
  /** A list of nodes. */
  nodes: Array<RaidVideo>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type RaidVideoEdge = {
  __typename?: 'RaidVideoEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node: Maybe<RaidVideo>;
};

export type Recruitment = {
  __typename?: 'Recruitment';
  endAt: Maybe<Scalars['ISO8601DateTime']['output']>;
  pickup: Scalars['Boolean']['output'];
  recruitmentGroup: RecruitmentGroup;
  recruitmentType: RecruitmentTypeEnum;
  rerun: Scalars['Boolean']['output'];
  since: Scalars['ISO8601DateTime']['output'];
  startAt: Scalars['ISO8601DateTime']['output'];
  student: Maybe<Student>;
  studentName: Scalars['String']['output'];
  uid: Scalars['String']['output'];
  until: Maybe<Scalars['ISO8601DateTime']['output']>;
};

export type RecruitmentGroup = {
  __typename?: 'RecruitmentGroup';
  contentType: Maybe<Scalars['String']['output']>;
  contentUid: Maybe<Scalars['String']['output']>;
  endAt: Maybe<Scalars['ISO8601DateTime']['output']>;
  recruitmentType: RecruitmentTypeEnum;
  recruitments: Array<Recruitment>;
  startAt: Scalars['ISO8601DateTime']['output'];
  uid: Scalars['String']['output'];
};

export type RecruitmentInput = {
  pickup: InputMaybe<Scalars['Boolean']['input']>;
  recruitmentType: RecruitmentTypeEnum;
  rerun: InputMaybe<Scalars['Boolean']['input']>;
  studentName: Scalars['String']['input'];
  studentUid: InputMaybe<Scalars['String']['input']>;
  uid: Scalars['String']['input'];
};

export enum RecruitmentTypeEnum {
  Archive = 'archive',
  Encore = 'encore',
  Fes = 'fes',
  Given = 'given',
  Limited = 'limited',
  Recollect = 'recollect',
  Usual = 'usual'
}

export enum Region {
  Cn = 'cn',
  Gl = 'gl',
  Jp = 'jp'
}

export type ResourceInterface = {
  name: Scalars['String']['output'];
  rarity: Scalars['Int']['output'];
  type: ResourceTypeEnum;
  uid: Scalars['String']['output'];
};

export enum ResourceTypeEnum {
  Currency = 'currency',
  Equipment = 'equipment',
  Furniture = 'furniture',
  Item = 'item'
}

export enum RoleEnum {
  Special = 'special',
  Striker = 'striker'
}

export enum RunTypeEnum {
  First = 'first',
  Permanent = 'permanent',
  Rerun = 'rerun'
}

export type Skill = {
  __typename?: 'Skill';
  name: Scalars['String']['output'];
  skillType: StudentSkillTypeEnum;
};

export type SkillItem = {
  __typename?: 'SkillItem';
  amount: Scalars['Int']['output'];
  item: Item;
  skillLevel: Scalars['Int']['output'];
  skillType: StudentSkillItemTypeEnum;
  student: Student;
};

export type Student = {
  __typename?: 'Student';
  altNames: Array<Scalars['String']['output']>;
  attackType: Attack;
  birthday: Maybe<Scalars['ISO8601Date']['output']>;
  defenseType: Defense;
  equipments: Array<Scalars['String']['output']>;
  favoriteItems: Array<FavoriteItem>;
  gear: Maybe<Gear>;
  initialTier: Scalars['Int']['output'];
  name: Scalars['String']['output'];
  order: Scalars['Int']['output'];
  position: Position;
  recruitments: Array<Recruitment>;
  released: Scalars['Boolean']['output'];
  role: RoleEnum;
  schaleDbId: Maybe<Scalars['String']['output']>;
  school: Scalars['String']['output'];
  skillItems: Array<SkillItem>;
  skills: Array<Skill>;
  tacticRole: TacticRole;
  uid: Scalars['String']['output'];
};


export type StudentFavoriteItemsArgs = {
  favorited: InputMaybe<Scalars['Boolean']['input']>;
};


export type StudentSkillItemsArgs = {
  skillLevel: InputMaybe<Scalars['Int']['input']>;
  skillType: InputMaybe<StudentSkillItemTypeEnum>;
};


export type StudentSkillsArgs = {
  skillType: InputMaybe<StudentSkillTypeEnum>;
};

export enum StudentSkillItemTypeEnum {
  Ex = 'ex',
  Normal = 'normal'
}

export enum StudentSkillTypeEnum {
  Ex = 'ex',
  ExtraPassive = 'extra_passive',
  Passive = 'passive',
  Public = 'public'
}

export enum TacticRole {
  Attacker = 'attacker',
  Healer = 'healer',
  Support = 'support',
  TacticalSupport = 'tactical_support',
  Tank = 'tank'
}

export enum Terrain {
  Indoor = 'indoor',
  Outdoor = 'outdoor',
  Street = 'street'
}

/** Autogenerated input type of UpdateCampaign */
export type UpdateCampaignInput = {
  category: InputMaybe<Array<CategoryEnum>>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  endAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  multiplier: InputMaybe<Scalars['Int']['input']>;
  region: Region;
  startAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateCampaign. */
export type UpdateCampaignPayload = {
  __typename?: 'UpdateCampaignPayload';
  campaign: Maybe<Campaign>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
};

/** Autogenerated input type of UpdateEventContent */
export type UpdateEventContentInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  rawDataFirst: InputMaybe<Scalars['JSON']['input']>;
  rawDataRerun: InputMaybe<Scalars['JSON']['input']>;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateEventContent. */
export type UpdateEventContentPayload = {
  __typename?: 'UpdateEventContentPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  eventContent: Maybe<EventContent>;
};

/** Autogenerated input type of UpdateJointFiringDrill */
export type UpdateJointFiringDrillInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  confirmed: InputMaybe<Scalars['Boolean']['input']>;
  defenseType: InputMaybe<Defense>;
  drillType: InputMaybe<DrillTypeEnum>;
  season: InputMaybe<Scalars['Int']['input']>;
  terrain: InputMaybe<Terrain>;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateJointFiringDrill. */
export type UpdateJointFiringDrillPayload = {
  __typename?: 'UpdateJointFiringDrillPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  jointFiringDrill: Maybe<JointFiringDrill>;
};

/** Autogenerated input type of UpdateRaidBoss */
export type UpdateRaidBossInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  eventContentUid: InputMaybe<Scalars['String']['input']>;
  raidType: InputMaybe<BossTypeEnum>;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateRaidBoss. */
export type UpdateRaidBossPayload = {
  __typename?: 'UpdateRaidBossPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  raidBoss: Maybe<RaidBoss>;
};

/** Autogenerated input type of UpdateRaidSchedule */
export type UpdateRaidScheduleInput = {
  attackType: InputMaybe<Attack>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  defenseTypes: InputMaybe<Array<DefenseTypeInput>>;
  endAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  eventContentRunType: InputMaybe<EventScheduleRunTypeEnum>;
  jpSeasonIndex: InputMaybe<Scalars['Int']['input']>;
  raidBossUid: InputMaybe<Scalars['String']['input']>;
  raidType: InputMaybe<RaidScheduleTypeEnum>;
  region: InputMaybe<Region>;
  seasonIndex: InputMaybe<Scalars['Int']['input']>;
  startAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  terrain: InputMaybe<Terrain>;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateRaidSchedule. */
export type UpdateRaidSchedulePayload = {
  __typename?: 'UpdateRaidSchedulePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  raidSchedule: Maybe<RaidSchedule>;
};

/** Autogenerated input type of UpdateRecruitmentGroup */
export type UpdateRecruitmentGroupInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  content: InputMaybe<ContentReferenceInput>;
  endAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  recruitmentType: InputMaybe<RecruitmentTypeEnum>;
  startAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateRecruitmentGroup. */
export type UpdateRecruitmentGroupPayload = {
  __typename?: 'UpdateRecruitmentGroupPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  recruitmentGroup: Maybe<RecruitmentGroup>;
};

/** Autogenerated input type of UpdateRecruitment */
export type UpdateRecruitmentInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  pickup: InputMaybe<Scalars['Boolean']['input']>;
  recruitmentGroupUid: InputMaybe<Scalars['String']['input']>;
  recruitmentType: InputMaybe<RecruitmentTypeEnum>;
  rerun: InputMaybe<Scalars['Boolean']['input']>;
  studentName: InputMaybe<Scalars['String']['input']>;
  studentUid: InputMaybe<Scalars['String']['input']>;
  uid: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateRecruitment. */
export type UpdateRecruitmentPayload = {
  __typename?: 'UpdateRecruitmentPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  recruitment: Maybe<Recruitment>;
};

/** Autogenerated input type of UpsertEventContentSchedule */
export type UpsertEventContentScheduleInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  endAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  eventContentUid: Scalars['String']['input'];
  region: Region;
  runType: EventScheduleRunTypeEnum;
  startAt: Scalars['ISO8601DateTime']['input'];
};

/** Autogenerated return type of UpsertEventContentSchedule. */
export type UpsertEventContentSchedulePayload = {
  __typename?: 'UpsertEventContentSchedulePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  eventContentSchedule: Maybe<EventContentSchedule>;
};

/** Autogenerated input type of UpsertJointFiringDrillSchedule */
export type UpsertJointFiringDrillScheduleInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars['String']['input']>;
  drillUid: Scalars['String']['input'];
  endAt: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  region: Region;
  startAt: Scalars['ISO8601DateTime']['input'];
};

/** Autogenerated return type of UpsertJointFiringDrillSchedule. */
export type UpsertJointFiringDrillSchedulePayload = {
  __typename?: 'UpsertJointFiringDrillSchedulePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  jointFiringDrillSchedule: Maybe<JointFiringDrillSchedule>;
};

export enum VideoSortEnum {
  PublishedAtDesc = 'PUBLISHED_AT_DESC',
  ScoreDesc = 'SCORE_DESC'
}

export type CampaignNameQueryVariables = Exact<{
  uid: Scalars['String']['input'];
}>;


export type CampaignNameQuery = { __typename?: 'Query', campaign: { __typename?: 'Campaign', uid: string, category: Array<CategoryEnum>, multiplier: number } | null };

export type EventContentNameQueryVariables = Exact<{
  uid: Scalars['String']['input'];
}>;


export type EventContentNameQuery = { __typename?: 'Query', eventContent: { __typename?: 'EventContent', uid: string, name: string } | null };

export type MiniEventContentNameQueryVariables = Exact<{
  uid: Scalars['String']['input'];
}>;


export type MiniEventContentNameQuery = { __typename?: 'Query', miniEventContent: { __typename?: 'MiniEventContent', uid: string, name: string } | null };

export type JointFiringDrillNameQueryVariables = Exact<{
  uid: Scalars['String']['input'];
}>;


export type JointFiringDrillNameQuery = { __typename?: 'Query', jointFiringDrill: { __typename?: 'JointFiringDrill', uid: string, season: number, drillType: DrillTypeEnum } | null };

export type EventContentShopContentQueryVariables = Exact<{
  eventUid: Scalars['String']['input'];
  runType: RunTypeEnum;
}>;


export type EventContentShopContentQuery = { __typename?: 'Query', eventContent: { __typename?: 'EventContent', stages: Array<{ __typename?: 'EventContentStage', uid: string, stageNumber: string, stageIndex: number, stageType: string, enterCostAmount: number, rewards: Array<{ __typename?: 'EventContentStageReward', amount: number, probability: string, tag: string, resource:
          | { __typename: 'Currency', uid: string, name: string, rarity: number }
          | { __typename: 'Equipment', uid: string, name: string, rarity: number }
          | { __typename: 'Furniture', uid: string, name: string, rarity: number }
          | { __typename: 'Item', category: string, uid: string, name: string, rarity: number }
         | null }> }>, shopResources: Array<{ __typename?: 'EventContentShopResource', uid: string, resourceAmount: number, paymentResourceAmount: number, shopAmount: number | null, resource:
        | { __typename?: 'Currency', type: ResourceTypeEnum, uid: string, name: string, rarity: number }
        | { __typename?: 'Equipment', type: ResourceTypeEnum, uid: string, name: string, rarity: number }
        | { __typename?: 'Furniture', type: ResourceTypeEnum, uid: string, name: string, rarity: number }
        | { __typename?: 'Item', type: ResourceTypeEnum, uid: string, name: string, rarity: number }
       | null, paymentResource:
        | { __typename?: 'Currency', uid: string, name: string }
        | { __typename?: 'Equipment', uid: string, name: string }
        | { __typename?: 'Furniture', uid: string, name: string }
        | { __typename?: 'Item', uid: string, name: string }
       | null }>, bonuses: Array<{ __typename?: 'EventContentBonus', percentage: string, resource:
        | { __typename?: 'Currency', uid: string, name: string }
        | { __typename?: 'Equipment', uid: string, name: string }
        | { __typename?: 'Furniture', uid: string, name: string }
        | { __typename?: 'Item', uid: string, name: string }
       | null, student: { __typename?: 'Student', uid: string, name: string, role: RoleEnum } | null }>, minigameConfigs: Array<{ __typename?: 'EventMinigameConfig', minigameType: string, payment: { __typename?: 'EventMinigamePayment', quantity: number, resource:
          | { __typename?: 'Currency', type: ResourceTypeEnum, uid: string, name: string }
          | { __typename?: 'Equipment', type: ResourceTypeEnum, uid: string, name: string }
          | { __typename?: 'Furniture', type: ResourceTypeEnum, uid: string, name: string }
          | { __typename?: 'Item', type: ResourceTypeEnum, uid: string, name: string }
         | null }, rewardGroups: Array<{ __typename?: 'EventMinigameRewardGroup', condition: { __typename?: 'EventMinigameSlotCondition', type: string, value: number | null, values: Array<number> | null, divisor: number | null, remainders: Array<number> | null }, rewards: Array<{ __typename?: 'EventMinigameRewardItem', quantity: number, resource:
            | { __typename?: 'Currency', type: ResourceTypeEnum, uid: string, name: string, rarity: number }
            | { __typename?: 'Equipment', type: ResourceTypeEnum, uid: string, name: string, rarity: number }
            | { __typename?: 'Furniture', type: ResourceTypeEnum, uid: string, name: string, rarity: number }
            | { __typename?: 'Item', type: ResourceTypeEnum, uid: string, name: string, rarity: number }
           | null }> }> }> } | null };

export type MainStoriesQueryVariables = Exact<{ [key: string]: never; }>;


export type MainStoriesQuery = { __typename?: 'Query', mainStories: Array<{ __typename?: 'MainStoryVolume', uid: string, name: string | null, label: string, sortOrder: number, chapters: Array<{ __typename?: 'MainStoryChapter', uid: string, name: string | null, chapterNumber: number, parts: Array<{ __typename?: 'MainStoryPart', uid: string, name: string | null, episodeStart: number | null, episodeEnd: number | null, sortOrder: number, schedules: Array<{ __typename?: 'MainStoryPartSchedule', region: string, releasedAt: Date, confirmed: boolean }> }> }> }> };

export type RaidScheduleDetailQueryVariables = Exact<{
  uid: Scalars['String']['input'];
}>;


export type RaidScheduleDetailQuery = { __typename?: 'Query', raidSchedule: { __typename?: 'RaidSchedule', uid: string, raidType: string, seasonIndex: number, region: string, terrain: Terrain, startAt: Date | null, endAt: Date | null, attackType: Attack | null, raidBoss: { __typename?: 'RaidBoss', uid: string, name: string }, defenseTypes: Array<{ __typename?: 'DefenseTypeAndDifficulty', defenseType: Defense, difficulty: Difficulty | null }>, jpSchedule: { __typename?: 'RaidSchedule', uid: string, seasonIndex: number } | null, videos: { __typename?: 'RaidVideoConnection', pageInfo: { __typename?: 'PageInfo', hasNextPage: boolean } } } | null };

export type RaidScheduleBySeasonIndexQueryVariables = Exact<{
  region: Scalars['String']['input'];
  seasonIndex: Scalars['Int']['input'];
}>;


export type RaidScheduleBySeasonIndexQuery = { __typename?: 'Query', raidScheduleBySeasonIndex: { __typename?: 'RaidSchedule', uid: string, raidType: string, seasonIndex: number, region: string, terrain: Terrain, startAt: Date | null, endAt: Date | null, attackType: Attack | null, raidBoss: { __typename?: 'RaidBoss', uid: string, name: string }, defenseTypes: Array<{ __typename?: 'DefenseTypeAndDifficulty', defenseType: Defense, difficulty: Difficulty | null }>, jpSchedule: { __typename?: 'RaidSchedule', uid: string, seasonIndex: number } | null, videos: { __typename?: 'RaidVideoConnection', pageInfo: { __typename?: 'PageInfo', hasNextPage: boolean } } } | null };

export type AllRaidSchedulesQueryVariables = Exact<{
  region: Scalars['String']['input'];
}>;


export type AllRaidSchedulesQuery = { __typename?: 'Query', raidSchedules: { __typename?: 'RaidScheduleConnection', nodes: Array<{ __typename?: 'RaidSchedule', uid: string, raidType: string, seasonIndex: number, region: string, terrain: Terrain, startAt: Date | null, endAt: Date | null, attackType: Attack | null, raidBoss: { __typename?: 'RaidBoss', uid: string, name: string }, defenseTypes: Array<{ __typename?: 'DefenseTypeAndDifficulty', defenseType: Defense, difficulty: Difficulty | null }>, jpSchedule: { __typename?: 'RaidSchedule', uid: string, seasonIndex: number } | null }> } };

export type AllStudentsFavoriteItemsQueryVariables = Exact<{ [key: string]: never; }>;


export type AllStudentsFavoriteItemsQuery = { __typename?: 'Query', students: Array<{ __typename?: 'Student', uid: string, name: string, favoriteItems: Array<{ __typename?: 'FavoriteItem', favorited: boolean, favoriteLevel: number, exp: number, item: { __typename?: 'Item', uid: string, name: string, rarity: number } }> }> };

export type AllStudentsQueryVariables = Exact<{ [key: string]: never; }>;


export type AllStudentsQuery = { __typename?: 'Query', students: Array<{ __typename?: 'Student', uid: string, name: string, altNames: Array<string>, school: string, initialTier: number, order: number, attackType: Attack, defenseType: Defense, position: Position, tacticRole: TacticRole, birthday: any | null, role: RoleEnum, equipments: Array<string>, released: boolean }> };

export type StudentSkillItemsQueryVariables = Exact<{
  uid: Scalars['String']['input'];
}>;


export type StudentSkillItemsQuery = { __typename?: 'Query', student: { __typename?: 'Student', uid: string, schaleDbId: string | null, skillItems: Array<{ __typename?: 'SkillItem', item: { __typename?: 'Item', uid: string, subCategory: string | null, rarity: number } }> } };

export type RecruitmentGroupsListQueryVariables = Exact<{
  endAfter: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  uids: InputMaybe<Array<Scalars['String']['input']> | Scalars['String']['input']>;
}>;


export type RecruitmentGroupsListQuery = { __typename?: 'Query', recruitmentGroups: Array<{ __typename?: 'RecruitmentGroup', uid: string, contentType: string | null, contentUid: string | null, startAt: Date, endAt: Date | null, recruitmentType: RecruitmentTypeEnum, recruitments: Array<{ __typename?: 'Recruitment', recruitmentType: RecruitmentTypeEnum, pickup: boolean, rerun: boolean, since: Date, until: Date | null, studentName: string, student: { __typename?: 'Student', uid: string, attackType: Attack, defenseType: Defense, role: RoleEnum, name: string, schaleDbId: string | null } | null }> }> };

export type RaidForPartyQueryVariables = Exact<{ [key: string]: never; }>;


export type RaidForPartyQuery = { __typename?: 'Query', raids: { __typename?: 'RaidConnection', nodes: Array<{ __typename?: 'Raid', uid: string, name: string, type: RaidTypeEnum, boss: string, terrain: Terrain, since: Date }> } };

export type RaidForPartyEditQueryVariables = Exact<{ [key: string]: never; }>;


export type RaidForPartyEditQuery = { __typename?: 'Query', raids: { __typename?: 'RaidConnection', nodes: Array<{ __typename?: 'Raid', uid: string, name: string, type: RaidTypeEnum, boss: string, terrain: Terrain, since: Date, until: Date }> } };

export type StudentFavoriteItemQueryVariables = Exact<{
  uid: Scalars['String']['input'];
}>;


export type StudentFavoriteItemQuery = { __typename?: 'Query', student: { __typename?: 'Student', uid: string, name: string, favoriteItems: Array<{ __typename?: 'FavoriteItem', favorited: boolean, favoriteLevel: number, exp: number, item: { __typename?: 'Item', uid: string, name: string, rarity: number } }> } };

export type RaidScheduleVideosQueryVariables = Exact<{
  uid: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  after: InputMaybe<Scalars['String']['input']>;
  sort: InputMaybe<VideoSortEnum>;
}>;


export type RaidScheduleVideosQuery = { __typename?: 'Query', raidSchedule: { __typename?: 'RaidSchedule', videos: { __typename?: 'RaidVideoConnection', pageInfo: { __typename?: 'PageInfo', hasNextPage: boolean, hasPreviousPage: boolean, startCursor: string | null, endCursor: string | null }, edges: Array<{ __typename?: 'RaidVideoEdge', node: { __typename?: 'RaidVideo', id: string, title: string, score: number, youtubeId: string, thumbnailUrl: string, publishedAt: Date } | null }> } } | null };

export type RaidScheduleVideosDataQueryVariables = Exact<{
  uid: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  after: InputMaybe<Scalars['String']['input']>;
  sort: InputMaybe<VideoSortEnum>;
}>;


export type RaidScheduleVideosDataQuery = { __typename?: 'Query', raidSchedule: { __typename?: 'RaidSchedule', videos: { __typename?: 'RaidVideoConnection', pageInfo: { __typename?: 'PageInfo', hasNextPage: boolean, hasPreviousPage: boolean, startCursor: string | null, endCursor: string | null }, edges: Array<{ __typename?: 'RaidVideoEdge', node: { __typename?: 'RaidVideo', id: string, title: string, score: number, youtubeId: string, thumbnailUrl: string, publishedAt: Date } | null }> } } | null };

export type StudentGradeDetailQueryVariables = Exact<{
  uid: Scalars['String']['input'];
}>;


export type StudentGradeDetailQuery = { __typename?: 'Query', student: { __typename?: 'Student', name: string, uid: string, attackType: Attack, defenseType: Defense, role: RoleEnum, school: string, schaleDbId: string | null } };

export type StudentDetailQueryVariables = Exact<{
  uid: Scalars['String']['input'];
}>;


export type StudentDetailQuery = { __typename?: 'Query', student: { __typename?: 'Student', name: string, uid: string, attackType: Attack, defenseType: Defense, role: RoleEnum, school: string, schaleDbId: string | null, recruitments: Array<{ __typename?: 'Recruitment', since: Date, rerun: boolean, recruitmentGroup: { __typename?: 'RecruitmentGroup', uid: string, startAt: Date, endAt: Date | null } }> } };


export const CampaignNameDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"CampaignName"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"campaign"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"category"}},{"kind":"Field","name":{"kind":"Name","value":"multiplier"}}]}}]}}]} as unknown as DocumentNode<CampaignNameQuery, CampaignNameQueryVariables>;
export const EventContentNameDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"EventContentName"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"eventContent"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]} as unknown as DocumentNode<EventContentNameQuery, EventContentNameQueryVariables>;
export const MiniEventContentNameDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"MiniEventContentName"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"miniEventContent"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]} as unknown as DocumentNode<MiniEventContentNameQuery, MiniEventContentNameQueryVariables>;
export const JointFiringDrillNameDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"JointFiringDrillName"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"jointFiringDrill"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"season"}},{"kind":"Field","name":{"kind":"Name","value":"drillType"}}]}}]}}]} as unknown as DocumentNode<JointFiringDrillNameQuery, JointFiringDrillNameQueryVariables>;
export const EventContentShopContentDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"EventContentShopContent"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"eventUid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"runType"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"RunTypeEnum"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"eventContent"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"eventUid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"stages"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"runType"},"value":{"kind":"Variable","name":{"kind":"Name","value":"runType"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"stageNumber"}},{"kind":"Field","name":{"kind":"Name","value":"stageIndex"}},{"kind":"Field","name":{"kind":"Name","value":"stageType"}},{"kind":"Field","name":{"kind":"Name","value":"enterCostAmount"}},{"kind":"Field","name":{"kind":"Name","value":"rewards"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"amount"}},{"kind":"Field","name":{"kind":"Name","value":"probability"}},{"kind":"Field","name":{"kind":"Name","value":"tag"}},{"kind":"Field","name":{"kind":"Name","value":"resource"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"rarity"}},{"kind":"InlineFragment","typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Item"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"category"}}]}}]}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"shopResources"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"runType"},"value":{"kind":"Variable","name":{"kind":"Name","value":"runType"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"resourceAmount"}},{"kind":"Field","name":{"kind":"Name","value":"paymentResourceAmount"}},{"kind":"Field","name":{"kind":"Name","value":"shopAmount"}},{"kind":"Field","name":{"kind":"Name","value":"resource"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"rarity"}}]}},{"kind":"Field","name":{"kind":"Name","value":"paymentResource"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"bonuses"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"runType"},"value":{"kind":"Variable","name":{"kind":"Name","value":"runType"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"percentage"}},{"kind":"Field","name":{"kind":"Name","value":"resource"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"student"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"role"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"minigameConfigs"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"runType"},"value":{"kind":"Variable","name":{"kind":"Name","value":"runType"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"minigameType"}},{"kind":"Field","name":{"kind":"Name","value":"payment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"quantity"}},{"kind":"Field","name":{"kind":"Name","value":"resource"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"rewardGroups"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"condition"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"value"}},{"kind":"Field","name":{"kind":"Name","value":"values"}},{"kind":"Field","name":{"kind":"Name","value":"divisor"}},{"kind":"Field","name":{"kind":"Name","value":"remainders"}}]}},{"kind":"Field","name":{"kind":"Name","value":"rewards"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"quantity"}},{"kind":"Field","name":{"kind":"Name","value":"resource"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"rarity"}}]}}]}}]}}]}}]}}]}}]} as unknown as DocumentNode<EventContentShopContentQuery, EventContentShopContentQueryVariables>;
export const MainStoriesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"MainStories"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"mainStories"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"label"}},{"kind":"Field","name":{"kind":"Name","value":"sortOrder"}},{"kind":"Field","name":{"kind":"Name","value":"chapters"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"chapterNumber"}},{"kind":"Field","name":{"kind":"Name","value":"parts"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"episodeStart"}},{"kind":"Field","name":{"kind":"Name","value":"episodeEnd"}},{"kind":"Field","name":{"kind":"Name","value":"sortOrder"}},{"kind":"Field","name":{"kind":"Name","value":"schedules"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"region"}},{"kind":"Field","name":{"kind":"Name","value":"releasedAt"}},{"kind":"Field","name":{"kind":"Name","value":"confirmed"}}]}}]}}]}}]}}]}}]} as unknown as DocumentNode<MainStoriesQuery, MainStoriesQueryVariables>;
export const RaidScheduleDetailDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RaidScheduleDetail"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"raidSchedule"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"raidType"}},{"kind":"Field","name":{"kind":"Name","value":"seasonIndex"}},{"kind":"Field","name":{"kind":"Name","value":"region"}},{"kind":"Field","name":{"kind":"Name","value":"terrain"}},{"kind":"Field","name":{"kind":"Name","value":"startAt"}},{"kind":"Field","name":{"kind":"Name","value":"endAt"}},{"kind":"Field","name":{"kind":"Name","value":"attackType"}},{"kind":"Field","name":{"kind":"Name","value":"raidBoss"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"defenseTypes"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"defenseType"}},{"kind":"Field","name":{"kind":"Name","value":"difficulty"}}]}},{"kind":"Field","name":{"kind":"Name","value":"jpSchedule"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"seasonIndex"}}]}},{"kind":"Field","name":{"kind":"Name","value":"videos"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"first"},"value":{"kind":"IntValue","value":"1"}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"pageInfo"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"hasNextPage"}}]}}]}}]}}]}}]} as unknown as DocumentNode<RaidScheduleDetailQuery, RaidScheduleDetailQueryVariables>;
export const RaidScheduleBySeasonIndexDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RaidScheduleBySeasonIndex"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"region"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"seasonIndex"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"raidScheduleBySeasonIndex"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"region"},"value":{"kind":"Variable","name":{"kind":"Name","value":"region"}}},{"kind":"Argument","name":{"kind":"Name","value":"seasonIndex"},"value":{"kind":"Variable","name":{"kind":"Name","value":"seasonIndex"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"raidType"}},{"kind":"Field","name":{"kind":"Name","value":"seasonIndex"}},{"kind":"Field","name":{"kind":"Name","value":"region"}},{"kind":"Field","name":{"kind":"Name","value":"terrain"}},{"kind":"Field","name":{"kind":"Name","value":"startAt"}},{"kind":"Field","name":{"kind":"Name","value":"endAt"}},{"kind":"Field","name":{"kind":"Name","value":"attackType"}},{"kind":"Field","name":{"kind":"Name","value":"raidBoss"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"defenseTypes"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"defenseType"}},{"kind":"Field","name":{"kind":"Name","value":"difficulty"}}]}},{"kind":"Field","name":{"kind":"Name","value":"jpSchedule"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"seasonIndex"}}]}},{"kind":"Field","name":{"kind":"Name","value":"videos"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"first"},"value":{"kind":"IntValue","value":"1"}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"pageInfo"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"hasNextPage"}}]}}]}}]}}]}}]} as unknown as DocumentNode<RaidScheduleBySeasonIndexQuery, RaidScheduleBySeasonIndexQueryVariables>;
export const AllRaidSchedulesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"AllRaidSchedules"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"region"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"raidSchedules"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"region"},"value":{"kind":"Variable","name":{"kind":"Name","value":"region"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodes"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"raidType"}},{"kind":"Field","name":{"kind":"Name","value":"seasonIndex"}},{"kind":"Field","name":{"kind":"Name","value":"region"}},{"kind":"Field","name":{"kind":"Name","value":"terrain"}},{"kind":"Field","name":{"kind":"Name","value":"startAt"}},{"kind":"Field","name":{"kind":"Name","value":"endAt"}},{"kind":"Field","name":{"kind":"Name","value":"attackType"}},{"kind":"Field","name":{"kind":"Name","value":"raidBoss"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"defenseTypes"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"defenseType"}},{"kind":"Field","name":{"kind":"Name","value":"difficulty"}}]}},{"kind":"Field","name":{"kind":"Name","value":"jpSchedule"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"seasonIndex"}}]}}]}}]}}]}}]} as unknown as DocumentNode<AllRaidSchedulesQuery, AllRaidSchedulesQueryVariables>;
export const AllStudentsFavoriteItemsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"AllStudentsFavoriteItems"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"students"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"favoriteItems"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"favorited"}},{"kind":"Field","name":{"kind":"Name","value":"favoriteLevel"}},{"kind":"Field","name":{"kind":"Name","value":"exp"}},{"kind":"Field","name":{"kind":"Name","value":"item"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"rarity"}}]}}]}}]}}]}}]} as unknown as DocumentNode<AllStudentsFavoriteItemsQuery, AllStudentsFavoriteItemsQueryVariables>;
export const AllStudentsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"AllStudents"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"students"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"altNames"}},{"kind":"Field","name":{"kind":"Name","value":"school"}},{"kind":"Field","name":{"kind":"Name","value":"initialTier"}},{"kind":"Field","name":{"kind":"Name","value":"order"}},{"kind":"Field","name":{"kind":"Name","value":"attackType"}},{"kind":"Field","name":{"kind":"Name","value":"defenseType"}},{"kind":"Field","name":{"kind":"Name","value":"position"}},{"kind":"Field","name":{"kind":"Name","value":"tacticRole"}},{"kind":"Field","name":{"kind":"Name","value":"birthday"}},{"kind":"Field","name":{"kind":"Name","value":"role"}},{"kind":"Field","name":{"kind":"Name","value":"equipments"}},{"kind":"Field","name":{"kind":"Name","value":"released"}}]}}]}}]} as unknown as DocumentNode<AllStudentsQuery, AllStudentsQueryVariables>;
export const StudentSkillItemsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"StudentSkillItems"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"student"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"schaleDbId"}},{"kind":"Field","name":{"kind":"Name","value":"skillItems"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"skillType"},"value":{"kind":"EnumValue","value":"ex"}},{"kind":"Argument","name":{"kind":"Name","value":"skillLevel"},"value":{"kind":"IntValue","value":"5"}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"item"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"subCategory"}},{"kind":"Field","name":{"kind":"Name","value":"rarity"}}]}}]}}]}}]}}]} as unknown as DocumentNode<StudentSkillItemsQuery, StudentSkillItemsQueryVariables>;
export const RecruitmentGroupsListDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RecruitmentGroupsList"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endAfter"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ISO8601DateTime"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uids"}},"type":{"kind":"ListType","type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"recruitmentGroups"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"endAfter"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endAfter"}}},{"kind":"Argument","name":{"kind":"Name","value":"uids"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uids"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"contentType"}},{"kind":"Field","name":{"kind":"Name","value":"contentUid"}},{"kind":"Field","name":{"kind":"Name","value":"startAt"}},{"kind":"Field","name":{"kind":"Name","value":"endAt"}},{"kind":"Field","name":{"kind":"Name","value":"recruitmentType"}},{"kind":"Field","name":{"kind":"Name","value":"recruitments"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"recruitmentType"}},{"kind":"Field","name":{"kind":"Name","value":"pickup"}},{"kind":"Field","name":{"kind":"Name","value":"rerun"}},{"kind":"Field","name":{"kind":"Name","value":"since"}},{"kind":"Field","name":{"kind":"Name","value":"until"}},{"kind":"Field","name":{"kind":"Name","value":"studentName"}},{"kind":"Field","name":{"kind":"Name","value":"student"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"attackType"}},{"kind":"Field","name":{"kind":"Name","value":"defenseType"}},{"kind":"Field","name":{"kind":"Name","value":"role"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"schaleDbId"}}]}}]}}]}}]}}]} as unknown as DocumentNode<RecruitmentGroupsListQuery, RecruitmentGroupsListQueryVariables>;
export const RaidForPartyDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RaidForParty"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"raids"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodes"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"boss"}},{"kind":"Field","name":{"kind":"Name","value":"terrain"}},{"kind":"Field","name":{"kind":"Name","value":"since"}}]}}]}}]}}]} as unknown as DocumentNode<RaidForPartyQuery, RaidForPartyQueryVariables>;
export const RaidForPartyEditDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RaidForPartyEdit"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"raids"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodes"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"boss"}},{"kind":"Field","name":{"kind":"Name","value":"terrain"}},{"kind":"Field","name":{"kind":"Name","value":"since"}},{"kind":"Field","name":{"kind":"Name","value":"until"}}]}}]}}]}}]} as unknown as DocumentNode<RaidForPartyEditQuery, RaidForPartyEditQueryVariables>;
export const StudentFavoriteItemDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"StudentFavoriteItem"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"student"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"favoriteItems"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"favorited"}},{"kind":"Field","name":{"kind":"Name","value":"favoriteLevel"}},{"kind":"Field","name":{"kind":"Name","value":"exp"}},{"kind":"Field","name":{"kind":"Name","value":"item"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"rarity"}}]}}]}}]}}]}}]} as unknown as DocumentNode<StudentFavoriteItemQuery, StudentFavoriteItemQueryVariables>;
export const RaidScheduleVideosDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RaidScheduleVideos"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"first"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"after"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sort"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"VideoSortEnum"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"raidSchedule"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"videos"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"first"},"value":{"kind":"Variable","name":{"kind":"Name","value":"first"}}},{"kind":"Argument","name":{"kind":"Name","value":"after"},"value":{"kind":"Variable","name":{"kind":"Name","value":"after"}}},{"kind":"Argument","name":{"kind":"Name","value":"sort"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sort"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"pageInfo"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"hasNextPage"}},{"kind":"Field","name":{"kind":"Name","value":"hasPreviousPage"}},{"kind":"Field","name":{"kind":"Name","value":"startCursor"}},{"kind":"Field","name":{"kind":"Name","value":"endCursor"}}]}},{"kind":"Field","name":{"kind":"Name","value":"edges"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"node"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"score"}},{"kind":"Field","name":{"kind":"Name","value":"youtubeId"}},{"kind":"Field","name":{"kind":"Name","value":"thumbnailUrl"}},{"kind":"Field","name":{"kind":"Name","value":"publishedAt"}}]}}]}}]}}]}}]}}]} as unknown as DocumentNode<RaidScheduleVideosQuery, RaidScheduleVideosQueryVariables>;
export const RaidScheduleVideosDataDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RaidScheduleVideosData"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"first"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"after"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sort"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"VideoSortEnum"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"raidSchedule"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"videos"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"first"},"value":{"kind":"Variable","name":{"kind":"Name","value":"first"}}},{"kind":"Argument","name":{"kind":"Name","value":"after"},"value":{"kind":"Variable","name":{"kind":"Name","value":"after"}}},{"kind":"Argument","name":{"kind":"Name","value":"sort"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sort"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"pageInfo"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"hasNextPage"}},{"kind":"Field","name":{"kind":"Name","value":"hasPreviousPage"}},{"kind":"Field","name":{"kind":"Name","value":"startCursor"}},{"kind":"Field","name":{"kind":"Name","value":"endCursor"}}]}},{"kind":"Field","name":{"kind":"Name","value":"edges"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"node"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"score"}},{"kind":"Field","name":{"kind":"Name","value":"youtubeId"}},{"kind":"Field","name":{"kind":"Name","value":"thumbnailUrl"}},{"kind":"Field","name":{"kind":"Name","value":"publishedAt"}}]}}]}}]}}]}}]}}]} as unknown as DocumentNode<RaidScheduleVideosDataQuery, RaidScheduleVideosDataQueryVariables>;
export const StudentGradeDetailDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"StudentGradeDetail"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"student"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"attackType"}},{"kind":"Field","name":{"kind":"Name","value":"defenseType"}},{"kind":"Field","name":{"kind":"Name","value":"role"}},{"kind":"Field","name":{"kind":"Name","value":"school"}},{"kind":"Field","name":{"kind":"Name","value":"schaleDbId"}}]}}]}}]} as unknown as DocumentNode<StudentGradeDetailQuery, StudentGradeDetailQueryVariables>;
export const StudentDetailDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"StudentDetail"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"uid"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"student"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"uid"},"value":{"kind":"Variable","name":{"kind":"Name","value":"uid"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"attackType"}},{"kind":"Field","name":{"kind":"Name","value":"defenseType"}},{"kind":"Field","name":{"kind":"Name","value":"role"}},{"kind":"Field","name":{"kind":"Name","value":"school"}},{"kind":"Field","name":{"kind":"Name","value":"schaleDbId"}},{"kind":"Field","name":{"kind":"Name","value":"recruitments"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"since"}},{"kind":"Field","name":{"kind":"Name","value":"rerun"}},{"kind":"Field","name":{"kind":"Name","value":"recruitmentGroup"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uid"}},{"kind":"Field","name":{"kind":"Name","value":"startAt"}},{"kind":"Field","name":{"kind":"Name","value":"endAt"}}]}}]}}]}}]}}]} as unknown as DocumentNode<StudentDetailQuery, StudentDetailQueryVariables>;