import { readFileSync } from "node:fs";
import { describe, expect, test } from "@jest/globals";

describe("cache_refresh_jobs PostgreSQL migration contract", () => {
  const migration = readFileSync("db/postgres/migrations/20260823000100_create_cache_refresh_jobs.sql", "utf8");
  const schema = readFileSync("app/db/postgres/schema.ts", "utf8");

  test("defines the logical job fields with PostgreSQL timestamp and JSON types", () => {
    expect(migration).toMatch(
      /CREATE TABLE cache_refresh_jobs \([\s\S]*id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY[\s\S]*\);/,
    );
    expect(migration).toContain("requested_by integer NOT NULL");
    expect(migration).toContain("active_slot integer");
    expect(migration).toContain("current_task text");
    expect(migration).toContain("completed_count integer NOT NULL DEFAULT 0");
    expect(migration).toContain("total_count integer NOT NULL");
    expect(migration).toContain("task_results jsonb NOT NULL");
    expect(migration).toContain("started_at timestamptz");
    expect(migration).toContain("finished_at timestamptz");
    expect(migration).toContain("created_at timestamptz NOT NULL DEFAULT now()");
    expect(migration).toContain("updated_at timestamptz NOT NULL DEFAULT now()");
  });

  test("keeps Drizzle snake_case mappings and PostgreSQL types aligned", () => {
    expect(schema).toContain("export const pgCacheRefreshJobsTable = pgTable(");
    expect(schema).toMatch(/requestedBy: integer\("requested_by"\)/);
    expect(schema).toMatch(/activeSlot: integer\("active_slot"\)/);
    expect(schema).toMatch(/currentTask: text\("current_task"\)/);
    expect(schema).toMatch(/completedCount: integer\("completed_count"\)/);
    expect(schema).toMatch(/taskResults: jsonb\("task_results"\)/);
    expect(schema).toMatch(/startedAt: timestamptz\("started_at"\)/);
    expect(schema).toMatch(/finishedAt: timestamptz\("finished_at"\)/);
    expect(schema).toMatch(/createdAt: timestamptz\("created_at"\)/);
    expect(schema).toMatch(/updatedAt: timestamptz\("updated_at"\)/);
  });

  test("preserves a named partial active-slot invariant and latest-job ordering index", () => {
    expect(migration).toContain("cache_refresh_jobs_uid_uidx");
    expect(migration).toContain("cache_refresh_jobs_active_slot_uidx");
    expect(migration).toContain(
      "CREATE UNIQUE INDEX cache_refresh_jobs_active_slot_uidx\n  ON cache_refresh_jobs (active_slot)\n  WHERE active_slot IS NOT NULL;",
    );
    expect(migration).toContain(
      "CREATE INDEX cache_refresh_jobs_created_at_idx ON cache_refresh_jobs (created_at DESC);",
    );

    expect(schema).toContain('CACHE_REFRESH_ACTIVE_SLOT_INDEX_NAME = "cache_refresh_jobs_active_slot_uidx"');
    expect(schema).toContain("uniqueIndex(CACHE_REFRESH_ACTIVE_SLOT_INDEX_NAME)");
    expect(schema).toContain('index("cache_refresh_jobs_created_at_idx").on(table.createdAt.desc())');
  });
});
