import { readFileSync } from "node:fs";
import { describe, expect, test } from "@jest/globals";

const migration = readFileSync(
  "db/postgres/migrations/20260824000300_create_mollu_connect_auth_logs.sql",
  "utf8",
);
const schema = readFileSync("app/db/postgres/schema.ts", "utf8");
const apiKeyModel = readFileSync("app/models/connect-api-key.ts", "utf8");
const requestLogModel = readFileSync("app/models/connect-request-log.ts", "utf8");

describe("MolluConnect auth and request log PostgreSQL migration contract", () => {
  test("defines both tables with identity IDs, native JSON scopes, and timestamps", () => {
    for (const table of ["connect_api_keys", "connect_request_logs"]) {
      expect(migration).toMatch(new RegExp(`CREATE TABLE ${table} \\(`));
      expect(migration).toMatch(
        new RegExp(`CREATE TABLE ${table} \\([\\s\\S]*?id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`),
      );
    }
    expect(migration).toContain("scopes jsonb NOT NULL");
    expect(migration).toContain("created_at timestamptz NOT NULL DEFAULT now()");
    expect(migration).toContain("last_used_at timestamptz");
    expect(migration).toContain("revoked_at timestamptz");
  });

  test("preserves API key and request-log uniqueness/index contracts", () => {
    for (const index of [
      "connect_api_keys_uid_uidx",
      "connect_api_keys_key_prefix_idx",
      "connect_api_keys_user_id_idx",
      "connect_request_logs_uid_uidx",
      "connect_request_logs_api_key_created_at_idx",
    ]) {
      expect(migration).toContain(index);
    }
    expect(schema).toContain("export const pgConnectApiKeysTable = pgTable(");
    expect(schema).toContain("export const pgConnectRequestLogsTable = pgTable(");
  });

  test("removes D1 access from MolluLog's auth/log model wrappers", () => {
    expect(apiKeyModel).not.toMatch(/drizzle-orm\/(d1|sqlite-core)/);
    expect(requestLogModel).not.toMatch(/drizzle-orm\/(d1|sqlite-core)/);
  });
});
