import { readFileSync } from "node:fs";
import { describe, expect, test } from "@jest/globals";

const migration = readFileSync("db/postgres/migrations/20260824000200_create_event_shop_states.sql", "utf8");
const schema = readFileSync("app/db/postgres/schema.ts", "utf8");
const model = readFileSync("app/models/event-shop-state.ts", "utf8");

describe("event shop state PostgreSQL migration contract", () => {
  test("defines every D1 state field with identity, JSON, boolean, integer, and timestamps", () => {
    expect(migration).toMatch(
      /CREATE TABLE event_shop_states \([\s\S]*id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY[\s\S]*\);/,
    );
    for (const column of [
      "item_quantities jsonb NOT NULL",
      "item_purchase_days jsonb NOT NULL",
      "selected_bonus_student_uids jsonb NOT NULL",
      "selected_bonus_student_uids_by_item jsonb NOT NULL",
      "enabled_stages jsonb NOT NULL",
      "existing_payment_item_quantities jsonb NOT NULL",
      "extra_stage_runs jsonb NOT NULL",
      "overridden_required_quantities jsonb NOT NULL",
      "include_recruited_students boolean NOT NULL DEFAULT false",
      "include_first_clear boolean NOT NULL DEFAULT false",
      "minigame_start_round integer NOT NULL DEFAULT 1",
      "minigame_play_count integer NOT NULL DEFAULT 0",
      "created_at timestamptz NOT NULL DEFAULT now()",
      "updated_at timestamptz NOT NULL DEFAULT now()",
    ]) {
      expect(migration).toContain(column);
    }
    expect(migration).toContain("selected_payment_resource_uid text,");
    expect(migration).not.toContain("selected_payment_resource_uid text NOT NULL");
  });

  test("preserves UID and user/event uniqueness", () => {
    expect(migration).toContain("event_shop_states_uid_uidx");
    expect(migration).toContain("event_shop_states_user_event_uidx");
    expect(schema).toContain("export const pgEventShopStatesTable = pgTable(");
    expect(schema).toContain('uniqueIndex("event_shop_states_uid_uidx")');
    expect(schema).toContain('uniqueIndex("event_shop_states_user_event_uidx")');
  });

  test("keeps the model wrapper free of D1 access", () => {
    expect(model).not.toMatch(/drizzle-orm\/(d1|sqlite-core)/);
  });
});
