import { readFileSync } from "node:fs";
import { describe, expect, test } from "@jest/globals";

const tables = [
  "senseis",
  "auth_identities",
  "passkeys",
  "pending_sensei_registrations",
  "sensei_privacies",
  "followerships",
] as const;

describe("identity PostgreSQL migration contract", () => {
  const migration = readFileSync("db/postgres/migrations/20260822000200_create_identity.sql", "utf8");
  const schema = readFileSync("app/db/postgres/schema.ts", "utf8");

  test("defines exactly the six identity tables with timestamp and identity IDs", () => {
    for (const table of tables) {
      expect(migration).toMatch(new RegExp(`CREATE TABLE ${table} \\(`));
      expect(migration).toMatch(
        new RegExp(`CREATE TABLE ${table} \\([\\s\\S]*?id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`),
      );
    }
    expect(migration).toContain("created_at timestamptz NOT NULL DEFAULT now()");
    expect(migration).toContain("updated_at timestamptz NOT NULL DEFAULT now()");
  });

  test("preserves the required unique keys without DB CHECK constraints", () => {
    expect(migration).toContain("followerships_follower_followee_uidx");
    expect(migration).toContain("passkeys_uid_uidx");
    expect(migration).toContain("auth_identities_provider_user_uidx");
    expect(migration).not.toMatch(/CHECK\s*\(/i);
    expect(schema).toContain('uniqueIndex("followerships_follower_followee_uidx")');
    expect(schema).toContain('uniqueIndex("passkeys_uid_uidx")');
    expect(schema).not.toContain('check("senseis_');
  });

  test("does not add production foreign keys as part of this cutover", () => {
    expect(migration).not.toMatch(/FOREIGN KEY|REFERENCES\s+/i);
  });
});
