import { readFileSync } from "node:fs";
import { describe, expect, test } from "@jest/globals";

const migration = readFileSync("db/postgres/migrations/20260824000100_create_pickup_histories.sql", "utf8");
const schema = readFileSync("app/db/postgres/schema.ts", "utf8");
const model = readFileSync("app/models/pickup-history.ts", "utf8");

describe("pickup history PostgreSQL migration contract", () => {
  test("defines the D1 columns with identity, PostgreSQL JSON, and timestamps", () => {
    expect(migration).toMatch(
      /CREATE TABLE pickup_histories \([\s\S]*id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY[\s\S]*\);/,
    );
    expect(migration).toContain("user_id integer NOT NULL");
    expect(migration).toContain("event_id text NOT NULL");
    expect(migration).toContain("result jsonb NOT NULL");
    expect(migration).toContain("created_at timestamptz NOT NULL DEFAULT now()");
    expect(migration).toContain("updated_at timestamptz NOT NULL DEFAULT now()");
  });

  test("preserves UID uniqueness and user lookup", () => {
    expect(migration).toContain("pickup_histories_uid_uidx");
    expect(migration).toContain("pickup_histories_user_id_idx");
    expect(schema).toContain("export const pgPickupHistoriesTable = pgTable(");
    expect(schema).toContain('uniqueIndex("pickup_histories_uid_uidx")');
    expect(schema).toContain('index("pickup_histories_user_id_idx")');
  });

  test("keeps the model wrapper free of D1 access", () => {
    expect(model).not.toMatch(/drizzle-orm\/(d1|sqlite-core)/);
  });
});
