import { readFileSync } from "node:fs";
import { describe, expect, it } from "@jest/globals";

const migration = readFileSync("db/postgres/migrations/20260927000200_create_planner_states.sql", "utf8");
const schema = readFileSync("app/db/postgres/schema.ts", "utf8");

describe("planner states PostgreSQL migration contract", () => {
  it("adds the versioned JSON document table with one row per user and no domain CHECK constraints", () => {
    expect(migration).toMatch(
      /CREATE TABLE planner_states \([\s\S]*id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY[\s\S]*user_id integer NOT NULL[\s\S]*revision integer NOT NULL[\s\S]*document jsonb NOT NULL[\s\S]*created_at timestamptz NOT NULL DEFAULT now\(\)[\s\S]*updated_at timestamptz NOT NULL DEFAULT now\(\)[\s\S]*\);/,
    );
    expect(migration).toContain("CREATE UNIQUE INDEX planner_states_user_id_uidx ON planner_states (user_id)");
    expect(migration).not.toMatch(/CHECK\s*\(/i);
    expect(schema).toContain('"planner_states"');
    expect(schema).toContain('uniqueIndex("planner_states_user_id_uidx").on(table.userId)');
    expect(schema).toContain("jsonb().$type<PlannerStateDocumentV1>().notNull()");
  });
});
