import { readFileSync } from "node:fs";
import { describe, expect, test } from "@jest/globals";

const migration = readFileSync("db/postgres/migrations/20260823000200_create_pyroxene_planner.sql", "utf8");
const schema = readFileSync("app/db/postgres/schema.ts", "utf8");
const plannerModel = readFileSync("app/models/pyroxene-planner.ts", "utf8");
const guestModel = readFileSync("app/models/guest-pyroxene-import.ts", "utf8");

describe("Pyroxene PostgreSQL migration contract", () => {
  test("defines all six tables with identity IDs and exact D1 metadata columns", () => {
    for (const table of [
      "pyroxene_owned_resources",
      "pyroxene_collected_sources",
      "pyroxene_timeline_items",
      "pyroxene_planner_options",
      "pyroxene_event_data",
      "pyroxene_guest_import_items",
    ]) {
      expect(migration).toMatch(new RegExp(`CREATE TABLE ${table} \\(`));
      expect(migration).toMatch(
        new RegExp(`CREATE TABLE ${table} \\([\\s\\S]*?id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`),
      );
    }
    expect(migration).toContain("input_at timestamptz NOT NULL");
    expect(migration).toContain("collected_at timestamptz NOT NULL");
    expect(migration).toContain("auto_repurchase boolean NOT NULL DEFAULT false");
    expect(migration).toContain("completed boolean NOT NULL DEFAULT false");
    expect(migration).toContain("imported_at timestamptz NOT NULL DEFAULT now()");
    const collectedTable = migration.match(/CREATE TABLE pyroxene_collected_sources \(([\s\S]*?)\);/)?.[1] ?? "";
    const guestTable = migration.match(/CREATE TABLE pyroxene_guest_import_items \(([\s\S]*?)\);/)?.[1] ?? "";
    expect(collectedTable).not.toContain("updated_at");
    expect(guestTable).not.toContain("created_at");
    expect(guestTable).not.toContain("updated_at");
  });

  test("keeps every physical D1 uniqueness contract and no foreign keys/checks", () => {
    for (const index of [
      "pyroxene_owned_resources_uid_uidx",
      "pyroxene_collected_sources_uid_uidx",
      "pyroxene_collected_sources_user_source_key_uidx",
      "pyroxene_timeline_items_uid_uidx",
      "pyroxene_planner_options_user_id_uidx",
      "pyroxene_event_data_uid_uidx",
      "pyroxene_event_data_user_event_uid_uidx",
      "pyroxene_guest_import_items_user_dataset_item_uidx",
    ]) {
      expect(migration).toContain(index);
    }
    expect(migration).not.toMatch(/FOREIGN KEY|REFERENCES\s+/i);
    expect(migration).not.toMatch(/CHECK\s*\(/i);
  });

  test("maps the six table columns through the PostgreSQL Drizzle schema", () => {
    expect(schema).toContain("export const pgPyroxeneOwnedResourcesTable = pgTable(");
    expect(schema).toContain("export const pgPyroxeneCollectedSourcesTable = pgTable(");
    expect(schema).toContain("export const pgPyroxeneTimelineItemsTable = pgTable(");
    expect(schema).toContain("export const pgPyroxenePlannerOptionsTable = pgTable(");
    expect(schema).toContain("export const pgPyroxeneEventDataTable = pgTable(");
    expect(schema).toContain("export const pgPyroxeneGuestImportItemsTable = pgTable(");
    expect(schema).toMatch(/inputAt: timestamptz\("input_at"\)/);
    expect(schema).toMatch(/sourceKey: text\("source_key"\)/);
    expect(schema).toMatch(/autoRepurchase: boolean\("auto_repurchase"\)/);
    expect(schema).toMatch(/completed: boolean\(\)/);
    expect(schema).toMatch(/importedAt: timestamptz\("imported_at"\)/);
  });

  test("keeps model wrappers free of D1 and direct PostgreSQL client imports", () => {
    for (const source of [plannerModel, guestModel]) {
      expect(source).not.toMatch(/drizzle-orm\/(d1|sqlite-core)/);
      expect(source).not.toMatch(/drizzle-orm\/node-postgres/);
      expect(source).not.toMatch(/from ["']pg["']/);
    }
  });
});
