import { readFileSync } from "node:fs";
import { describe, expect, test } from "@jest/globals";

const migration = readFileSync("db/postgres/migrations/20260919000100_create_student_summary_revisions.sql", "utf8");
const schema = readFileSync("app/db/postgres/schema.ts", "utf8");
const model = readFileSync("app/models/student-summary.server.ts", "utf8");

describe("student summary revision PostgreSQL migration contract", () => {
  test("defines the mirrored revision columns with identity, jsonb, and timestamps", () => {
    expect(migration).toMatch(
      /CREATE TABLE student_summary_revisions \([\s\S]*id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY[\s\S]*\);/,
    );
    for (const column of [
      "student_uid text NOT NULL",
      "generated_summary text NOT NULL",
      "summary text NOT NULL",
      "source_catalog_version text NOT NULL",
      "source_hash text NOT NULL",
      "source_snapshot jsonb NOT NULL",
      "provider text,",
      "model text,",
      "prompt_version text NOT NULL",
      "published_at timestamptz,",
      "created_at timestamptz NOT NULL DEFAULT now()",
      "updated_at timestamptz NOT NULL DEFAULT now()",
    ]) {
      expect(migration).toContain(column);
    }
  });

  test("stays PostgreSQL 14 compatible with insert-only revisions and no CHECK constraints", () => {
    expect(migration).not.toContain("NULLS NOT DISTINCT");
    expect(migration).not.toMatch(/\bCHECK\b/i);
    expect(migration).not.toMatch(/CREATE UNIQUE INDEX/);
    expect(migration).toContain("CREATE INDEX student_summary_revisions_student_published_at_id_idx");
    expect(migration).toContain("ON student_summary_revisions (student_uid, published_at DESC, id DESC)");
  });

  test("mirrors the table in the drizzle schema with explicit snake_case columns", () => {
    expect(schema).toContain("export const pgStudentSummaryRevisionsTable = pgTable(");
    const tableBlock = schema.slice(
      schema.indexOf("export const pgStudentSummaryRevisionsTable = pgTable("),
      schema.indexOf("export const", schema.indexOf("export const pgStudentSummaryRevisionsTable = pgTable(") + 1),
    );
    expect(tableBlock).not.toContain("uniqueIndex");
    expect(schema).toContain('index("student_summary_revisions_student_published_at_id_idx")');
    expect(schema).toContain('text("student_uid")');
    expect(schema).toContain('text("generated_summary")');
    expect(schema).toContain('text("source_catalog_version")');
    expect(schema).toContain('text("source_hash")');
    expect(schema).toContain('jsonb("source_snapshot")');
    expect(schema).toContain('text("prompt_version")');
    expect(schema).toContain('timestamptz("published_at")');
  });

  test("keeps the published read path behind the server-only model wrapper", () => {
    expect(model).toContain("getPostgresPublishedStudentSummary");
    expect(model).not.toMatch(/from "pg"/);
    expect(model).not.toContain("createPostgresClient");
  });
});
