create table content_favorite_students (
  id integer generated by default as identity primary key,
  uid text not null,
  user_id integer not null,
  student_id text not null,
  content_id text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index content_favorite_students_uid_uidx
  on content_favorite_students (uid);
create unique index content_favorite_students_user_content_student_uidx
  on content_favorite_students (user_id, content_id, student_id);
create index content_favorite_students_student_content_idx
  on content_favorite_students (student_id, content_id);
create index content_favorite_students_user_content_idx
  on content_favorite_students (user_id, content_id);
