create table coupons (
  id integer generated by default as identity primary key,
  uid text not null,
  name text not null,
  code text not null,
  image_url text,
  rewards jsonb not null default '[]'::jsonb,
  link_url text,
  link_label text,
  expires_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index coupons_uid_uidx on coupons (uid);
create unique index coupons_code_uidx on coupons (code);
create index coupons_expires_at_idx on coupons (expires_at);

create table coupon_registrations (
  id integer generated by default as identity primary key,
  uid text not null,
  user_id integer not null,
  coupon_id integer not null references coupons(id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index coupon_registrations_user_coupon_uidx
  on coupon_registrations (user_id, coupon_id);
create index coupon_registrations_user_id_idx
  on coupon_registrations (user_id);
