create table feedback_tickets (
  id integer generated by default as identity primary key,
  uid text not null,
  user_id integer not null,
  title text not null,
  content text not null,
  additional jsonb,
  status text not null default 'waiting',
  reply_email text,
  last_seen_admin_reply_id integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index feedback_tickets_uid_uidx on feedback_tickets (uid);
create index feedback_tickets_user_updated_at_idx
  on feedback_tickets (user_id, updated_at desc, id desc);

create table feedback_replies (
  id integer generated by default as identity primary key,
  uid text not null,
  ticket_id integer not null references feedback_tickets(id) on delete cascade,
  user_id integer not null,
  is_admin boolean not null default false,
  content text not null,
  created_at timestamptz not null
);

create unique index feedback_replies_uid_uidx on feedback_replies (uid);
create index feedback_replies_ticket_created_at_idx
  on feedback_replies (ticket_id, created_at, id);
create index feedback_replies_ticket_admin_id_idx
  on feedback_replies (ticket_id, is_admin, id);
