BEGIN;

-- Reserve the account-level notification natural key before a job row is
-- inserted.  The reservation is deliberately separate from the deployed
-- job indexes so old Ayumu workers can continue omitting logical_uid while
-- newer workers use channel_uid = null.
CREATE TABLE notification_job_dedup_keys (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  trigger text NOT NULL,
  source_uid text NOT NULL,
  generation integer NOT NULL,
  owner_channel_uid text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX notification_job_dedup_keys_natural_uidx
  ON notification_job_dedup_keys (user_id, trigger, source_uid, generation);
CREATE INDEX notification_job_dedup_keys_owner_channel_idx
  ON notification_job_dedup_keys (owner_channel_uid);

-- Prefer an existing logical row when the first deployment already contains
-- both legacy and logical-shaped jobs for a key.  Otherwise retain a legacy
-- channel owner so the old worker can keep its existing per-channel upsert.
INSERT INTO notification_job_dedup_keys
  (user_id, trigger, source_uid, generation, owner_channel_uid, created_at, updated_at)
SELECT user_id,
       trigger,
       source_uid,
       generation,
       CASE WHEN bool_or(channel_uid IS NULL) THEN NULL ELSE min(channel_uid) END,
       min(created_at),
       max(updated_at)
  FROM notification_jobs
 GROUP BY user_id, trigger, source_uid, generation;

CREATE FUNCTION notification_jobs_reserve_dedup_key() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  reservation_owner text;
BEGIN
  INSERT INTO notification_job_dedup_keys
    (user_id, trigger, source_uid, generation, owner_channel_uid, created_at, updated_at)
  VALUES
    (NEW.user_id, NEW.trigger, NEW.source_uid, NEW.generation, NEW.channel_uid, NEW.created_at, NEW.updated_at)
  ON CONFLICT (user_id, trigger, source_uid, generation) DO NOTHING;

  SELECT owner_channel_uid
    INTO reservation_owner
    FROM notification_job_dedup_keys
   WHERE user_id = NEW.user_id
     AND trigger = NEW.trigger
     AND source_uid = NEW.source_uid
     AND generation = NEW.generation;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'notification job deduplication reservation disappeared';
  END IF;

  -- A reservation is either logical (owner_channel_uid is null) or legacy
  -- (owner_channel_uid is non-null).  Repeated inserts of the same shape are
  -- allowed to reach the existing job upsert; the opposite shape is skipped.
  IF (NEW.channel_uid IS NULL) IS DISTINCT FROM (reservation_owner IS NULL) THEN
    RETURN NULL;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER notification_jobs_reserve_dedup_key
  BEFORE INSERT ON notification_jobs
  FOR EACH ROW EXECUTE FUNCTION notification_jobs_reserve_dedup_key();

COMMIT;
