CREATE TABLE community_author_mutes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  muted_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX community_author_mutes_user_id_uidx ON community_author_mutes (user_id);
CREATE INDEX community_author_mutes_muted_at_idx ON community_author_mutes (muted_at);
