ALTER TABLE ocr_jobs
  ADD COLUMN job_kind text NOT NULL DEFAULT 'item_inventory_images_v1';

CREATE INDEX ocr_jobs_user_kind_created_idx
  ON ocr_jobs (user_id, job_kind, created_at DESC);

CREATE TABLE ocr_video_inputs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL UNIQUE,
  job_uid text NOT NULL UNIQUE,
  object_key text NOT NULL UNIQUE,
  original_filename text NOT NULL,
  content_type text NOT NULL,
  byte_size bigint NOT NULL,
  input_sha256 text NOT NULL,
  status text NOT NULL DEFAULT 'pending_upload',
  generation integer NOT NULL DEFAULT 1,
  current_attempt_uid text,
  duration_ms integer,
  width integer,
  height integer,
  codec text,
  container text,
  last_error_code text,
  last_error_message text,
  raw_input_purge_after timestamptz NOT NULL,
  raw_input_deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE INDEX ocr_video_inputs_status_purge_idx
  ON ocr_video_inputs (status, raw_input_purge_after);
