CREATE TABLE event_shop_state_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  event_uid text NOT NULL,
  state jsonb NOT NULL,
  source text NOT NULL DEFAULT 'autosave',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX event_shop_state_history_user_event_created_idx ON event_shop_state_history (user_id, event_uid, created_at DESC);
