create table posts (
  id integer generated by default as identity primary key,
  uid text not null,
  title text not null,
  content text not null,
  board text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index posts_uid_uidx on posts (uid);
create index posts_board_created_at_uid_idx on posts (board, created_at desc, uid desc);
