BEGIN;

-- Keep activation history separate from ordinary channel updates so a logical
-- job can target only channels that were active when it was planned.
ALTER TABLE notification_channels ADD COLUMN activated_at timestamptz;
UPDATE notification_channels
   SET activated_at = COALESCE(verified_at, created_at)
 WHERE status = 'active' AND activated_at IS NULL;

-- Keep every deployed Discord job as an independent historical row. New
-- logical notifications leave channel_uid null and are deduplicated by the
-- account-level natural key below.
ALTER TABLE notification_jobs ADD COLUMN logical_uid text;
UPDATE notification_jobs SET logical_uid = uid WHERE logical_uid IS NULL;
ALTER TABLE notification_jobs ADD COLUMN delivery_snapshot_at timestamptz;

-- Ayumu versions that predate logical jobs omit logical_uid. Fill it from the
-- existing row UID before PostgreSQL enforces the new non-null contract.
CREATE FUNCTION notification_jobs_fill_logical_uid() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.logical_uid IS NULL OR btrim(NEW.logical_uid) = '' THEN
    NEW.logical_uid := NEW.uid;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER notification_jobs_fill_logical_uid
  BEFORE INSERT ON notification_jobs
  FOR EACH ROW EXECUTE FUNCTION notification_jobs_fill_logical_uid();

ALTER TABLE notification_jobs ALTER COLUMN logical_uid SET NOT NULL;
ALTER TABLE notification_jobs ALTER COLUMN channel_uid DROP NOT NULL;

CREATE INDEX notification_jobs_logical_uid_idx
  ON notification_jobs (logical_uid);
CREATE UNIQUE INDEX notification_jobs_logical_dedup_uidx
  ON notification_jobs (user_id, trigger, source_uid, generation)
  WHERE channel_uid IS NULL;

CREATE TABLE notification_push_subscriptions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  channel_uid text NOT NULL,
  user_id integer NOT NULL,
  endpoint_ciphertext text NOT NULL,
  p256dh_ciphertext text NOT NULL,
  auth_ciphertext text NOT NULL,
  endpoint_fingerprint text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  activated_at timestamptz,
  expires_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX notification_push_subscriptions_uid_uidx
  ON notification_push_subscriptions (uid);
CREATE UNIQUE INDEX notification_push_subscriptions_fingerprint_uidx
  ON notification_push_subscriptions (endpoint_fingerprint);
CREATE INDEX notification_push_subscriptions_user_status_idx
  ON notification_push_subscriptions (user_id, status);
CREATE INDEX notification_push_subscriptions_channel_uid_idx
  ON notification_push_subscriptions (channel_uid);

CREATE TABLE notification_deliveries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  notification_job_uid text NOT NULL,
  user_id integer NOT NULL,
  target_type text NOT NULL,
  target_uid text NOT NULL,
  channel_uid text,
  subscription_uid text,
  status text NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  provider_accepted_at timestamptz,
  ambiguous_at timestamptz,
  clicked_at timestamptz,
  delivered_at timestamptz,
  available_at timestamptz NOT NULL,
  last_error text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX notification_deliveries_uid_uidx
  ON notification_deliveries (uid);
CREATE UNIQUE INDEX notification_deliveries_job_target_uidx
  ON notification_deliveries (notification_job_uid, target_type, target_uid);
CREATE INDEX notification_deliveries_job_status_idx
  ON notification_deliveries (notification_job_uid, status);
CREATE INDEX notification_deliveries_user_id_idx
  ON notification_deliveries (user_id);

COMMIT;
