BEGIN;

DROP TABLE discord_notification_jobs;
DROP TABLE discord_notification_subscriptions;

CREATE TABLE notification_channels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  channel_type text NOT NULL,
  recipient_key text NOT NULL,
  status text NOT NULL,
  failure_reason text,
  verified_at timestamptz,
  last_verification_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX notification_channels_uid_uidx
  ON notification_channels (uid);
CREATE UNIQUE INDEX notification_channels_user_channel_type_uidx
  ON notification_channels (user_id, channel_type);
CREATE UNIQUE INDEX notification_channels_channel_type_recipient_key_uidx
  ON notification_channels (channel_type, recipient_key);
CREATE INDEX notification_channels_status_idx
  ON notification_channels (status);

CREATE TABLE notification_preferences (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  notification_type text NOT NULL,
  enabled boolean NOT NULL,
  lead_hours integer NOT NULL,
  effective_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX notification_preferences_user_notification_type_uidx
  ON notification_preferences (user_id, notification_type);

CREATE TABLE notification_jobs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  channel_uid text NOT NULL,
  trigger text NOT NULL,
  source_uid text NOT NULL,
  source_anchor timestamptz NOT NULL,
  planned_send_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  payload jsonb NOT NULL,
  generation integer NOT NULL,
  status text NOT NULL,
  publish_attempts integer NOT NULL,
  delivery_attempts integer NOT NULL,
  available_at timestamptz NOT NULL,
  publishing_at timestamptz,
  published_at timestamptz,
  delivered_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX notification_jobs_uid_uidx
  ON notification_jobs (uid);
CREATE UNIQUE INDEX notification_jobs_dedup_uidx
  ON notification_jobs (channel_uid, trigger, source_uid, generation);
CREATE INDEX notification_jobs_due_idx
  ON notification_jobs (status, planned_send_at);
CREATE INDEX notification_jobs_publish_idx
  ON notification_jobs (status, available_at);
CREATE INDEX notification_jobs_channel_uid_idx
  ON notification_jobs (channel_uid);
CREATE INDEX notification_jobs_user_id_idx
  ON notification_jobs (user_id);

COMMIT;
