create table coupons (
  id integer generated by default as identity primary key,
  uid text not null,
  name text not null,
  code text not null,
  image_url text,
  rewards jsonb not null default '[]'::jsonb,
  link_url text,
  link_label text,
  expires_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index coupons_uid_uidx on coupons (uid);
create unique index coupons_code_uidx on coupons (code);
create index coupons_expires_at_idx on coupons (expires_at);

create table coupon_registrations (
  id integer generated by default as identity primary key,
  uid text not null,
  user_id integer not null,
  coupon_id integer not null references coupons(id) on delete cascade,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index coupon_registrations_user_coupon_uidx
  on coupon_registrations (user_id, coupon_id);
create index coupon_registrations_user_id_idx
  on coupon_registrations (user_id);

create table feedback_tickets (
  id integer generated by default as identity primary key,
  uid text not null,
  user_id integer not null,
  title text not null,
  content text not null,
  additional jsonb,
  status text not null default 'waiting',
  reply_email text,
  last_seen_admin_reply_id integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index feedback_tickets_uid_uidx on feedback_tickets (uid);
create index feedback_tickets_user_updated_at_idx
  on feedback_tickets (user_id, updated_at desc, id desc);

create table feedback_replies (
  id integer generated by default as identity primary key,
  uid text not null,
  ticket_id integer not null references feedback_tickets(id) on delete cascade,
  user_id integer not null,
  is_admin boolean not null default false,
  content text not null,
  created_at timestamptz not null
);

create unique index feedback_replies_uid_uidx on feedback_replies (uid);
create index feedback_replies_ticket_created_at_idx
  on feedback_replies (ticket_id, created_at, id);
create index feedback_replies_ticket_admin_id_idx
  on feedback_replies (ticket_id, is_admin, id);
