CREATE TABLE student_states (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  student_uid text NOT NULL,
  recruited_student_uid text,
  relationship_level_uid text,
  tier integer,
  level integer,
  skill_ex integer,
  skill_normal integer,
  skill_enhanced integer,
  skill_sub integer,
  equip1 integer,
  equip2 integer,
  equip3 integer,
  equip_special integer,
  equip1_level integer,
  equip2_level integer,
  equip3_level integer,
  weapon_level integer,
  ability_hp integer,
  ability_atk integer,
  ability_heal integer,
  relationship_current_level integer,
  relationship_current_exp integer,
  recruited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX student_states_uid_uidx ON student_states (uid);
CREATE UNIQUE INDEX student_states_user_student_uidx ON student_states (user_id, student_uid);
CREATE INDEX student_states_user_id_idx ON student_states (user_id);

CREATE TABLE student_targets (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  student_uid text NOT NULL,
  student_growth_uid text,
  relationship_level_uid text,
  target_level integer,
  target_skill_ex integer,
  target_skill_normal integer,
  target_skill_enhanced integer,
  target_skill_sub integer,
  target_equip1 integer,
  target_equip2 integer,
  target_equip3 integer,
  target_equip_special integer,
  target_tier integer,
  target_weapon_level integer,
  target_ability_hp integer,
  target_ability_atk integer,
  target_ability_heal integer,
  relationship_target_level integer,
  gift_plan jsonb NOT NULL DEFAULT '{}'::jsonb,
  planner_added_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX student_targets_uid_uidx ON student_targets (uid);
CREATE UNIQUE INDEX student_targets_user_student_uidx ON student_targets (user_id, student_uid);
CREATE INDEX student_targets_user_id_idx ON student_targets (user_id);

CREATE TABLE student_state_audits (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  student_uid text NOT NULL,
  actor_user_id integer NOT NULL,
  source text NOT NULL,
  source_ref text,
  before_state jsonb NOT NULL,
  after_state jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX student_state_audits_user_student_created_idx
  ON student_state_audits (user_id, student_uid, created_at);

CREATE TABLE student_state_migration_control (
  key text PRIMARY KEY,
  nullable_semantics_enabled boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO student_state_migration_control (key, nullable_semantics_enabled)
VALUES ('default', false);
