CREATE TABLE knowledge_entries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  published_revision_id integer,
  archived_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX knowledge_entries_kind_id_idx
  ON knowledge_entries (kind, id);

CREATE INDEX knowledge_entries_active_published_idx
  ON knowledge_entries (kind, id)
  WHERE archived_at IS NULL AND published_revision_id IS NOT NULL;

CREATE TABLE knowledge_entry_revisions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id integer NOT NULL,
  title text NOT NULL,
  aliases jsonb NOT NULL,
  meaning_context text,
  inline_enabled boolean NOT NULL,
  generated_body text,
  body text,
  status text NOT NULL,
  generation_metadata jsonb,
  generation_request_id text,
  generation_started_at timestamptz,
  generated_at timestamptz,
  published_at timestamptz,
  rejected_at timestamptz,
  rejection_feedback text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX knowledge_entry_revisions_entry_id_id_idx
  ON knowledge_entry_revisions (entry_id, id);

CREATE INDEX knowledge_entry_revisions_draft_entry_idx
  ON knowledge_entry_revisions (entry_id)
  WHERE status = 'draft';

CREATE INDEX knowledge_entry_revisions_entry_status_updated_idx
  ON knowledge_entry_revisions (entry_id, status, updated_at DESC);
