CREATE TABLE event_shop_states (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  event_uid text NOT NULL,
  item_quantities jsonb NOT NULL DEFAULT '{}'::jsonb,
  item_purchase_days jsonb NOT NULL DEFAULT '{}'::jsonb,
  selected_bonus_student_uids jsonb NOT NULL DEFAULT '[]'::jsonb,
  bonus_student_selection_mode text NOT NULL DEFAULT 'shared',
  selected_bonus_student_uids_by_item jsonb NOT NULL DEFAULT '{}'::jsonb,
  enabled_stages jsonb NOT NULL DEFAULT '{}'::jsonb,
  include_recruited_students boolean NOT NULL DEFAULT false,
  existing_payment_item_quantities jsonb NOT NULL DEFAULT '{}'::jsonb,
  selected_payment_resource_uid text,
  include_first_clear boolean NOT NULL DEFAULT false,
  extra_stage_runs jsonb NOT NULL DEFAULT '{}'::jsonb,
  minigame_start_round integer NOT NULL DEFAULT 1,
  minigame_play_count integer NOT NULL DEFAULT 0,
  minigame_payment_quantity_mode text NOT NULL DEFAULT 'expected',
  overridden_required_quantities jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX event_shop_states_uid_uidx ON event_shop_states (uid);
CREATE UNIQUE INDEX event_shop_states_user_event_uidx ON event_shop_states (user_id, event_uid);
CREATE INDEX event_shop_states_user_id_idx ON event_shop_states (user_id);
