CREATE TABLE student_summary_revisions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_uid text NOT NULL,
  generated_summary text NOT NULL,
  summary text NOT NULL,
  source_catalog_version text NOT NULL,
  source_hash text NOT NULL,
  source_snapshot jsonb NOT NULL,
  provider text,
  model text,
  prompt_version text NOT NULL,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX student_summary_revisions_identity_uidx
  ON student_summary_revisions (student_uid, source_hash, prompt_version, COALESCE(provider, ''), COALESCE(model, ''));

CREATE INDEX student_summary_revisions_student_published_at_id_idx
  ON student_summary_revisions (student_uid, published_at DESC, id DESC);
