CREATE TABLE recruited_students (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  student_uid text NOT NULL,
  tier integer NOT NULL,
  level integer,
  skill_ex integer,
  skill_normal integer,
  skill_enhanced integer,
  skill_sub integer,
  equip1 integer,
  equip2 integer,
  equip3 integer,
  equip_special integer,
  weapon_level integer,
  ability_hp integer,
  ability_atk integer,
  ability_heal integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX recruited_students_uid_uidx ON recruited_students (uid);
CREATE UNIQUE INDEX recruited_students_user_student_uidx ON recruited_students (user_id, student_uid);
CREATE INDEX recruited_students_user_id_idx ON recruited_students (user_id);
CREATE INDEX recruited_students_student_uid_idx ON recruited_students (student_uid);

CREATE TABLE student_growth (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  student_uid text NOT NULL,
  level integer,
  skill_ex integer,
  skill_normal integer,
  skill_enhanced integer,
  skill_sub integer,
  equip1 integer,
  equip2 integer,
  equip3 integer,
  equip_special integer,
  target_level integer,
  target_skill_ex integer,
  target_skill_normal integer,
  target_skill_enhanced integer,
  target_skill_sub integer,
  target_equip1 integer,
  target_equip2 integer,
  target_equip3 integer,
  target_equip_special integer,
  target_tier integer,
  target_weapon_level integer,
  target_ability_hp integer,
  target_ability_atk integer,
  target_ability_heal integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX student_growth_uid_uidx ON student_growth (uid);
CREATE UNIQUE INDEX student_growth_user_student_uidx ON student_growth (user_id, student_uid);
CREATE INDEX student_growth_user_id_idx ON student_growth (user_id);

CREATE TABLE user_relationship_levels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  student_id text NOT NULL,
  current_level integer NOT NULL,
  current_exp integer,
  target_level integer NOT NULL,
  items jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_relationship_levels_items_object CHECK (jsonb_typeof(items) = 'object')
);
CREATE UNIQUE INDEX user_relationship_levels_uid_uidx ON user_relationship_levels (uid);
CREATE UNIQUE INDEX user_relationship_levels_user_student_uidx ON user_relationship_levels (user_id, student_id);
CREATE INDEX user_relationship_levels_user_id_idx ON user_relationship_levels (user_id);

CREATE TABLE growth_resource_inventory (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  item_uid text NOT NULL,
  quantity integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX growth_resource_inventory_uid_uidx ON growth_resource_inventory (uid);
CREATE UNIQUE INDEX growth_resource_inventory_user_item_uidx ON growth_resource_inventory (user_id, item_uid);
CREATE INDEX growth_resource_inventory_user_id_idx ON growth_resource_inventory (user_id);

CREATE TABLE sync_drafts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  api_key_uid text,
  source text NOT NULL DEFAULT 'connect',
  source_ref text,
  type text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  tool_name text,
  tool_version text,
  catalog_version text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  applied_at timestamptz,
  expires_at timestamptz
);
CREATE UNIQUE INDEX sync_drafts_uid_uidx ON sync_drafts (uid);
CREATE UNIQUE INDEX sync_drafts_user_source_ref_uidx ON sync_drafts (user_id, source, source_ref) WHERE source_ref IS NOT NULL;
CREATE INDEX sync_drafts_user_status_idx ON sync_drafts (user_id, status);

CREATE TABLE sync_draft_entries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  draft_uid text NOT NULL,
  entry_key text NOT NULL,
  value integer NOT NULL,
  value_json text,
  meta text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX sync_draft_entries_uid_uidx ON sync_draft_entries (uid);
CREATE UNIQUE INDEX sync_draft_entries_draft_entry_uidx ON sync_draft_entries (draft_uid, entry_key);
CREATE INDEX sync_draft_entries_draft_uid_idx ON sync_draft_entries (draft_uid, id);

CREATE TABLE user_resource_inventory_drafts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  applied_at timestamptz
);
CREATE UNIQUE INDEX user_resource_inventory_drafts_uid_uidx ON user_resource_inventory_drafts (uid);
CREATE INDEX user_resource_inventory_drafts_user_status_idx ON user_resource_inventory_drafts (user_id, status);

CREATE TABLE user_resource_inventory_draft_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  draft_uid text NOT NULL,
  item_uid text NOT NULL,
  quantity integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX user_resource_inventory_draft_items_uid_uidx ON user_resource_inventory_draft_items (uid);
CREATE UNIQUE INDEX user_resource_inventory_draft_items_draft_item_uidx ON user_resource_inventory_draft_items (draft_uid, item_uid);
CREATE INDEX user_resource_inventory_draft_items_draft_uid_idx ON user_resource_inventory_draft_items (draft_uid);
