ALTER TABLE timeline_contents
  ADD COLUMN reward_exchange_end_at timestamptz;
CREATE INDEX timeline_contents_reward_exchange_end_at_idx
  ON timeline_contents (reward_exchange_end_at);

CREATE TABLE discord_connections (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  discord_user_id text NOT NULL,
  status text NOT NULL DEFAULT 'unlinked',
  failure_reason text,
  verified_at timestamptz,
  last_verification_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT discord_connections_status_check CHECK (status IN ('unlinked', 'pending', 'active', 'failed'))
);
CREATE UNIQUE INDEX discord_connections_uid_uidx ON discord_connections (uid);
CREATE UNIQUE INDEX discord_connections_user_id_uidx ON discord_connections (user_id);
CREATE UNIQUE INDEX discord_connections_discord_user_id_uidx ON discord_connections (discord_user_id);
CREATE INDEX discord_connections_status_idx ON discord_connections (status);

CREATE TABLE discord_notification_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  event_start_enabled boolean NOT NULL DEFAULT false,
  event_end_enabled boolean NOT NULL DEFAULT false,
  reward_exchange_end_enabled boolean NOT NULL DEFAULT false,
  recruitment_start_enabled boolean NOT NULL DEFAULT false,
  timing_mode text NOT NULL DEFAULT 'day-before',
  kst_hour integer NOT NULL DEFAULT 11,
  effective_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT discord_notification_settings_timing_mode_check CHECK (timing_mode IN ('day-before', 'same-day')),
  CONSTRAINT discord_notification_settings_kst_hour_check CHECK (kst_hour BETWEEN 0 AND 23)
);
CREATE UNIQUE INDEX discord_notification_settings_user_id_uidx ON discord_notification_settings (user_id);

CREATE TABLE discord_recruitment_schedules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  timeline_content_uid text NOT NULL,
  student_uid text NOT NULL,
  recruitment_uid text NOT NULL,
  recruitment_group_uid text NOT NULL,
  student_name text,
  since timestamptz,
  until timestamptz,
  effective_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX discord_recruitment_schedules_uid_uidx ON discord_recruitment_schedules (uid);
CREATE UNIQUE INDEX discord_recruitment_schedules_user_content_student_recruitment_uidx
  ON discord_recruitment_schedules (user_id, timeline_content_uid, student_uid, recruitment_uid);
CREATE INDEX discord_recruitment_schedules_user_id_idx ON discord_recruitment_schedules (user_id);
CREATE INDEX discord_recruitment_schedules_since_idx ON discord_recruitment_schedules (since, user_id);

CREATE TABLE discord_notification_jobs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  trigger text NOT NULL,
  source_uid text NOT NULL,
  source_anchor timestamptz NOT NULL,
  planned_send_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  payload jsonb NOT NULL,
  generation integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0,
  published_at timestamptz,
  delivered_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX discord_notification_jobs_uid_uidx ON discord_notification_jobs (uid);
CREATE UNIQUE INDEX discord_notification_jobs_dedup_uidx
  ON discord_notification_jobs (user_id, trigger, source_uid, generation, planned_send_at);
CREATE INDEX discord_notification_jobs_due_idx ON discord_notification_jobs (status, planned_send_at);
CREATE INDEX discord_notification_jobs_user_id_idx ON discord_notification_jobs (user_id);

CREATE TABLE discord_notification_outbox (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  job_uid text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0,
  available_at timestamptz NOT NULL DEFAULT now(),
  publishing_at timestamptz,
  published_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX discord_notification_outbox_uid_uidx ON discord_notification_outbox (uid);
CREATE UNIQUE INDEX discord_notification_outbox_job_uid_uidx ON discord_notification_outbox (job_uid);
CREATE INDEX discord_notification_outbox_claim_idx ON discord_notification_outbox (status, available_at);
