-- Recruitment-opinion filter: per-account hide setting plus a 1:1
-- extension table holding the classifier state for event opinions.
ALTER TABLE senseis
  ADD COLUMN hide_recruitment_opinions boolean NOT NULL DEFAULT false;

CREATE TABLE community_post_recruitment_opinions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_uid text NOT NULL,
  recruitment_period_start_at timestamptz,
  recruitment_opinion_classification_status text,
  recruitment_opinion_classification text,
  recruitment_opinion_classification_revision integer NOT NULL DEFAULT 0,
  recruitment_opinion_classification_model text,
  recruitment_opinion_classification_prompt_version text,
  recruitment_opinion_classified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX community_post_recruitment_opinions_post_uid_uidx
  ON community_post_recruitment_opinions (post_uid);

CREATE INDEX community_post_recruitment_opinions_classification_status_idx
  ON community_post_recruitment_opinions (recruitment_opinion_classification_status);
