CREATE TABLE ocr_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL UNIQUE,
  user_id integer NOT NULL,
  status text NOT NULL DEFAULT 'uploading',
  generation integer NOT NULL DEFAULT 1,
  total_images integer NOT NULL,
  completed_images integer NOT NULL DEFAULT 0,
  failed_images integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  submitted_at timestamptz,
  completed_at timestamptz,
  expires_at timestamptz NOT NULL
);

CREATE INDEX ocr_jobs_user_created_idx ON ocr_jobs (user_id, created_at DESC);
CREATE INDEX ocr_jobs_status_updated_idx ON ocr_jobs (status, updated_at);

CREATE TABLE ocr_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL UNIQUE,
  job_uid text NOT NULL REFERENCES ocr_jobs(uid) ON DELETE CASCADE,
  object_key text NOT NULL UNIQUE,
  original_filename text NOT NULL,
  content_type text NOT NULL,
  byte_size integer NOT NULL,
  input_sha256 text NOT NULL,
  status text NOT NULL DEFAULT 'pending_upload',
  generation integer NOT NULL DEFAULT 1,
  current_attempt_uid text,
  last_error_code text,
  last_error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE INDEX ocr_images_job_status_idx ON ocr_images (job_uid, status);

CREATE TABLE ocr_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL UNIQUE,
  task_type text NOT NULL,
  task_uid text NOT NULL,
  generation integer NOT NULL,
  worker_id text NOT NULL,
  status text NOT NULL DEFAULT 'processing',
  queue_attempts integer NOT NULL DEFAULT 1,
  error_code text,
  error_message text,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz
);

CREATE INDEX ocr_attempts_task_idx ON ocr_attempts (task_type, task_uid, generation);

CREATE TABLE ocr_image_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL UNIQUE,
  image_uid text NOT NULL REFERENCES ocr_images(uid) ON DELETE CASCADE,
  generation integer NOT NULL,
  attempt_uid text NOT NULL REFERENCES ocr_attempts(uid),
  result_json jsonb NOT NULL,
  model_version text NOT NULL,
  catalog_version text NOT NULL,
  schema_version text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (image_uid, generation)
);

CREATE TABLE ocr_job_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL UNIQUE,
  job_uid text NOT NULL REFERENCES ocr_jobs(uid) ON DELETE CASCADE,
  generation integer NOT NULL,
  attempt_uid text NOT NULL REFERENCES ocr_attempts(uid),
  result_json jsonb NOT NULL,
  model_version text NOT NULL,
  catalog_version text NOT NULL,
  schema_version text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (job_uid, generation)
);

CREATE TABLE ocr_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL UNIQUE,
  event_type text NOT NULL,
  aggregate_uid text NOT NULL,
  generation integer NOT NULL,
  payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0,
  available_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (event_type, aggregate_uid, generation)
);

CREATE INDEX ocr_outbox_dispatch_idx ON ocr_outbox (status, available_at, id);
