CREATE TABLE cache_refresh_jobs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  requested_by integer NOT NULL,
  status text NOT NULL,
  active_slot integer,
  current_task text,
  completed_count integer NOT NULL DEFAULT 0,
  total_count integer NOT NULL,
  task_results jsonb NOT NULL,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX cache_refresh_jobs_uid_uidx ON cache_refresh_jobs (uid);
CREATE UNIQUE INDEX cache_refresh_jobs_active_slot_uidx
  ON cache_refresh_jobs (active_slot)
  WHERE active_slot IS NOT NULL;
CREATE INDEX cache_refresh_jobs_created_at_idx ON cache_refresh_jobs (created_at DESC);
