CREATE TABLE raid_walkthrough_likes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  walkthrough_uid text NOT NULL REFERENCES raid_walkthroughs(uid) ON DELETE CASCADE,
  user_id integer NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE UNIQUE INDEX raid_walkthrough_likes_walkthrough_user_uidx
  ON raid_walkthrough_likes (walkthrough_uid, user_id);

CREATE INDEX raid_walkthrough_likes_user_walkthrough_idx
  ON raid_walkthrough_likes (user_id, walkthrough_uid);
