CREATE TABLE connect_api_keys (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  name text NOT NULL,
  key_prefix text NOT NULL,
  key_hash text NOT NULL,
  scopes jsonb NOT NULL DEFAULT '["catalog:read", "draft:write"]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  last_used_at timestamptz,
  revoked_at timestamptz
);

CREATE UNIQUE INDEX connect_api_keys_uid_uidx ON connect_api_keys (uid);
CREATE INDEX connect_api_keys_key_prefix_idx ON connect_api_keys (key_prefix);
CREATE INDEX connect_api_keys_user_id_idx ON connect_api_keys (user_id);

CREATE TABLE connect_request_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  api_key_uid text,
  endpoint text NOT NULL,
  status integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX connect_request_logs_uid_uidx ON connect_request_logs (uid);
CREATE INDEX connect_request_logs_api_key_created_at_idx
  ON connect_request_logs (api_key_uid, created_at);
