ALTER TABLE timeline_contents
  ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX timeline_contents_id_uidx ON timeline_contents (id);

ALTER TABLE feedback_replies
  ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE raid_walkthroughs
  ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX raid_walkthroughs_id_uidx ON raid_walkthroughs (id);

ALTER TABLE raid_walkthrough_likes
  ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE ocr_attempts
  ADD COLUMN created_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE ocr_image_results
  ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE ocr_job_results
  ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE site_banners
  ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX site_banners_id_uidx ON site_banners (id);

ALTER TABLE community_post_likes
  ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE community_post_tags
  ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
