ALTER TABLE timeline_contents
  ADD COLUMN reward_exchange_end_at timestamptz;
CREATE INDEX timeline_contents_reward_exchange_end_at_idx
  ON timeline_contents (reward_exchange_end_at);

CREATE TABLE discord_notification_subscriptions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  discord_user_id text NOT NULL,
  status text NOT NULL,
  failure_reason text,
  verified_at timestamptz,
  last_verification_at timestamptz,
  event_start_enabled boolean NOT NULL,
  event_end_enabled boolean NOT NULL,
  reward_exchange_end_enabled boolean NOT NULL,
  recruitment_start_enabled boolean NOT NULL,
  timing_mode text NOT NULL,
  kst_hour integer NOT NULL,
  effective_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX discord_notification_subscriptions_uid_uidx
  ON discord_notification_subscriptions (uid);
CREATE UNIQUE INDEX discord_notification_subscriptions_user_id_uidx
  ON discord_notification_subscriptions (user_id);
CREATE UNIQUE INDEX discord_notification_subscriptions_discord_user_id_uidx
  ON discord_notification_subscriptions (discord_user_id);
CREATE INDEX discord_notification_subscriptions_status_idx
  ON discord_notification_subscriptions (status);

CREATE TABLE discord_notification_jobs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  trigger text NOT NULL,
  source_uid text NOT NULL,
  source_anchor timestamptz NOT NULL,
  planned_send_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  payload jsonb NOT NULL,
  generation integer NOT NULL,
  status text NOT NULL,
  publish_attempts integer NOT NULL,
  delivery_attempts integer NOT NULL,
  available_at timestamptz NOT NULL,
  publishing_at timestamptz,
  published_at timestamptz,
  delivered_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX discord_notification_jobs_uid_uidx
  ON discord_notification_jobs (uid);
CREATE UNIQUE INDEX discord_notification_jobs_dedup_uidx
  ON discord_notification_jobs (user_id, trigger, source_uid, generation, planned_send_at);
CREATE INDEX discord_notification_jobs_due_idx
  ON discord_notification_jobs (status, planned_send_at);
CREATE INDEX discord_notification_jobs_publish_idx
  ON discord_notification_jobs (status, available_at);
CREATE INDEX discord_notification_jobs_user_id_idx
  ON discord_notification_jobs (user_id);
