CREATE TABLE senseis (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  username text NOT NULL,
  friend_code text,
  profile_student_id text,
  google_id text,
  github_id text,
  active boolean NOT NULL DEFAULT false,
  bio text,
  role text NOT NULL DEFAULT 'guest',
  profile_visibility text NOT NULL DEFAULT 'public',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX senseis_uid_uidx ON senseis (uid);
CREATE UNIQUE INDEX senseis_username_uidx ON senseis (username);
CREATE UNIQUE INDEX senseis_google_id_uidx ON senseis (google_id);
CREATE UNIQUE INDEX senseis_github_id_uidx ON senseis (github_id);

CREATE TABLE auth_identities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensei_id integer NOT NULL,
  provider text NOT NULL,
  provider_user_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX auth_identities_provider_user_uidx
  ON auth_identities (provider, provider_user_id);
CREATE INDEX auth_identities_sensei_id_idx ON auth_identities (sensei_id);

CREATE TABLE passkeys (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  memo text NOT NULL,
  key_id text NOT NULL,
  public_key text NOT NULL,
  raw_request text NOT NULL,
  counter integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX passkeys_uid_uidx ON passkeys (uid);
CREATE UNIQUE INDEX passkeys_key_id_uidx ON passkeys (key_id);
CREATE INDEX passkeys_user_id_idx ON passkeys (user_id);

CREATE TABLE pending_sensei_registrations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  provider text NOT NULL,
  provider_user_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX pending_sensei_registrations_uid_uidx
  ON pending_sensei_registrations (uid);
CREATE UNIQUE INDEX pending_sensei_registrations_provider_user_uidx
  ON pending_sensei_registrations (provider, provider_user_id);

CREATE TABLE sensei_privacies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  member_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX sensei_privacies_user_id_uidx ON sensei_privacies (user_id);

CREATE TABLE followerships (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id integer NOT NULL,
  followee_id integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX followerships_follower_followee_uidx
  ON followerships (follower_id, followee_id);
CREATE INDEX followerships_follower_id_idx ON followerships (follower_id);
CREATE INDEX followerships_followee_id_idx ON followerships (followee_id);
