CREATE TABLE knowledge_entries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  published_revision_id integer,
  archived_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX knowledge_entries_kind_id_idx
  ON knowledge_entries (kind, id);

CREATE INDEX knowledge_entries_active_published_idx
  ON knowledge_entries (kind, id)
  WHERE archived_at IS NULL AND published_revision_id IS NOT NULL;

CREATE TABLE knowledge_entry_revisions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id integer NOT NULL REFERENCES knowledge_entries (id) ON DELETE RESTRICT,
  title text NOT NULL,
  aliases jsonb NOT NULL,
  meaning_context text,
  inline_enabled boolean NOT NULL,
  generated_body text,
  body text,
  status text NOT NULL,
  generation_metadata jsonb,
  generation_request_id text,
  generation_started_at timestamptz,
  generated_at timestamptz,
  published_at timestamptz,
  rejected_at timestamptz,
  rejection_feedback text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX knowledge_entry_revisions_entry_id_id_uidx
  ON knowledge_entry_revisions (entry_id, id);

ALTER TABLE knowledge_entries
  ADD CONSTRAINT knowledge_entries_published_revision_entry_fk
  FOREIGN KEY (id, published_revision_id)
  REFERENCES knowledge_entry_revisions (entry_id, id)
  ON DELETE RESTRICT;

CREATE UNIQUE INDEX knowledge_entry_revisions_one_draft_per_entry_uidx
  ON knowledge_entry_revisions (entry_id)
  WHERE status = 'draft';

CREATE INDEX knowledge_entry_revisions_entry_status_updated_idx
  ON knowledge_entry_revisions (entry_id, status, updated_at DESC);
