CREATE TABLE pickup_histories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  event_id text NOT NULL,
  result jsonb NOT NULL,
  raw_result text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX pickup_histories_uid_uidx ON pickup_histories (uid);
CREATE INDEX pickup_histories_user_id_idx ON pickup_histories (user_id);
