CREATE TABLE pyroxene_owned_resources (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  input_at timestamptz NOT NULL,
  pyroxene integer NOT NULL,
  one_time_ticket integer NOT NULL,
  ten_time_ticket integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX pyroxene_owned_resources_uid_uidx ON pyroxene_owned_resources (uid);
CREATE INDEX pyroxene_owned_resources_user_input_at_idx ON pyroxene_owned_resources (user_id, input_at);

CREATE TABLE pyroxene_collected_sources (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  source_key text NOT NULL,
  collected_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX pyroxene_collected_sources_uid_uidx ON pyroxene_collected_sources (uid);
CREATE UNIQUE INDEX pyroxene_collected_sources_user_source_key_uidx
  ON pyroxene_collected_sources (user_id, source_key);

CREATE TABLE pyroxene_timeline_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  event_at timestamptz NOT NULL,
  source text NOT NULL,
  repeat_type text,
  repeat_interval_days integer,
  repeat_count integer,
  auto_repurchase boolean NOT NULL DEFAULT false,
  description text NOT NULL,
  pyroxene_delta integer NOT NULL,
  one_time_ticket_delta integer NOT NULL,
  ten_time_ticket_delta integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX pyroxene_timeline_items_uid_uidx ON pyroxene_timeline_items (uid);
CREATE INDEX pyroxene_timeline_items_user_event_at_idx ON pyroxene_timeline_items (user_id, event_at);

CREATE TABLE pyroxene_planner_options (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  options text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX pyroxene_planner_options_user_id_uidx ON pyroxene_planner_options (user_id);

CREATE TABLE pyroxene_event_data (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  event_uid text NOT NULL,
  completed boolean NOT NULL DEFAULT false,
  expected_trials integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX pyroxene_event_data_uid_uidx ON pyroxene_event_data (uid);
CREATE UNIQUE INDEX pyroxene_event_data_user_event_uid_uidx ON pyroxene_event_data (user_id, event_uid);

CREATE TABLE pyroxene_guest_import_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  dataset_id text NOT NULL,
  item_type text NOT NULL,
  item_key text NOT NULL,
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX pyroxene_guest_import_items_user_dataset_item_uidx
  ON pyroxene_guest_import_items (user_id, dataset_id, item_type, item_key);
