CREATE TABLE user_furniture_inventory (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid text NOT NULL,
  user_id integer NOT NULL,
  furniture_uid text NOT NULL,
  quantity integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX user_furniture_inventory_uid_uidx
  ON user_furniture_inventory (uid);

CREATE UNIQUE INDEX user_furniture_inventory_user_furniture_uidx
  ON user_furniture_inventory (user_id, furniture_uid);

CREATE INDEX user_furniture_inventory_user_id_idx
  ON user_furniture_inventory (user_id);
